//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EditorQuest.rc
//
#define ID_QUEST_LOAD                   3
#define ID_QUEST_SAVE                   4
#define ID_QUEST_NEW                    5
#define IDD_PAGE_QUEST_TREE             101
#define IDD_EDITORQUEST_DIALOG          102
#define IDD_PAGE_QUEST_BASIC            103
#define IDD_PAGE_QUEST_STEP             104
#define IDR_MAINFRAME                   128
#define IDR_MENU_QUEST                  129
#define IDD_DIALOG_INPUT                130
#define IDD_DIALOG_ITEMEDIT             131
#define IDD_DIALOG_ITEM                 132
#define IDD_DIALOG_CROW                 133
#define IDD_DIALOG_MOBGEN               134
#define IDD_DIALOG_SKILL                135
#define IDD_DIALOG_MAP                  136
#define IDD_DIALOG_SEARCH               137
#define IDC_STATIC_TOOL                 1000
#define IDC_BUTTON_CSV_LOAD             1001
#define IDC_BUTTON_CSV_SAVE             1002
#define IDC_BUTTON_TEXT_IMPORT          1003
#define IDC_BUTTON_TEXT_EXPORT          1004
#define IDC_EDIT_ID                     1004
#define IDC_TREE                        1005
#define IDC_EDIT_NAME                   1005
#define IDC_BUTTON_TEXT_EXPORT2         1005
#define IDC_BUTTON_CLASS_CONVERT        1005
#define IDC_BUTTON_SEARCH               1005
#define IDC_BUTTON_CREATE_NAME          1006
#define IDC_BUTTON_CLASS_CONVERT2       1006
#define IDC_BUTTON_SEARCH_QUEST         1006
#define IDC_BUTTON_CREATE_NAME2         1007
#define IDC_BUTTON_CREATE_ID            1007
#define IDC_BUTTON_SAVE                 1007
#define IDC_BUTTON_BACK                 1008
#define IDC_LIST_RESULT                 1008
#define IDC_BUTTON_CANCEL               1009
#define IDC_BUTTON_NEXT                 1010
#define IDC_COMBO_SEARCHTYPE            1010
#define IDC_EDIT_EDITVERSION            1011
#define IDC_EDIT_QUEST_NID              1012
#define IDC_EDIT_QUEST_FILENAME         1013
#define IDC_EDIT_SEARCH                 1013
#define IDC_EDIT_TITLE                  1014
#define IDC_BUTTON_GO                   1014
#define IDC_EDIT_COMMENT                1015
#define IDC_CHECK_REPEAT                1016
#define IDC_EDIT_STEP_TITLE             1016
#define IDC_CHECK_AGAIN                 1017
#define IDC_CHECK_GIVEUP                1018
#define IDC_EDIT_TALKNPC_COMMENT        1018
#define IDC_CHECK_PARTY                 1019
#define IDC_EDIT_GUARDNPC_COMMENT       1019
#define IDC_CHECK_PARTYQUEST            1020
#define IDC_EDIT_DIEMOB_COMMENT         1020
#define IDC_CHECK_ONLYONE_PROG          1021
#define IDC_EDIT_SEL_MID                1021
#define IDC_EDIT_REACH_MAP_COMMENT      1021
#define IDC_CHECK_LIMIT_NONDIE          1022
#define IDC_EDIT_SEL_SID                1022
#define IDC_EDIT_GUARD_MAP_COMMENT      1022
#define IDC_EDIT_LIMIT_TIME             1023
#define IDC_EDIT_SEL_NAME               1023
#define IDC_EDIT_REQ_QITEM_COMMENT      1023
#define IDC_EDIT_LIMIT_PARTYNUM         1024
#define IDC_EDIT_BEGIN_MONEY            1025
#define IDC_LIST_SELECT                 1025
#define IDC_EDIT_BEGIN_PARTYNUM         1026
#define IDC_COMBO_SCHOOL                1027
#define IDC_EDIT1                       1028
#define IDC_EDIT_START_LEVEL            1028
#define IDC_EDIT_MID                    1028
#define IDC_EDIT_TALKNPC_MID            1028
#define IDC_EDIT_GENITEM_MID            1028
#define IDC_EDIT2                       1029
#define IDC_EDIT_START_ITEM_MID         1029
#define IDC_EDIT_SID                    1029
#define IDC_EDIT_TALKNPC_SID            1029
#define IDC_EDIT_GENITEM_SID            1029
#define IDC_EDIT3                       1030
#define IDC_EDIT_START_ITEM_SID         1030
#define IDC_EDIT_DAMAGE                 1030
#define IDC_EDIT_TALKNPC_NAME           1030
#define IDC_EDIT_GENITEM                1030
#define IDC_STATIC_SEARCH_1             1030
#define IDC_EDIT4                       1031
#define IDC_EDIT_START_ITEM_NAME        1031
#define IDC_EDIT_DEFENSE                1031
#define IDC_EDIT_GUARDNPC_MID           1031
#define IDC_EDIT_GEN_NUM                1031
#define IDC_BUTTON1                     1032
#define IDC_BUTTON_ITEM_ADD             1032
#define IDC_EDIT_ELECTRIC               1032
#define IDC_BUTTON_STEP_ADD             1032
#define IDC_BUTTON_GENITEM              1032
#define IDC_BUTTON2                     1033
#define IDC_BUTTON_ITEM_DEL             1033
#define IDC_EDIT_FIRE                   1033
#define IDC_BUTTON_STEP_DEL             1033
#define IDC_BUTTON_GEN_MOB_ADD          1033
#define IDC_EDIT_START_SKILL_MID        1034
#define IDC_EDIT_ICE                    1034
#define IDC_BUTTON_STEP_MOVEUP          1034
#define IDC_EDIT_START_SKILL_SID        1035
#define IDC_EDIT_POISON                 1035
#define IDC_BUTTON_STEP_MOVEDOWN        1035
#define IDC_EDIT_START_SKILL_NAME       1036
#define IDC_EDIT_SPIRIT                 1036
#define IDC_EDIT_GUARDNPC_SID           1036
#define IDC_BUTTON_SKILL_ADD            1037
#define IDC_EDIT_TURNNUM                1037
#define IDC_EDIT_GUARDNPC_NAME          1037
#define IDC_BUTTON_SKILL_DEL            1038
#define IDC_EDIT_DIEMOB_MID             1038
#define IDC_EDIT_START_QUEST_MAP_MID    1039
#define IDC_EDIT_DIEMOB_SID             1039
#define IDC_EDIT_START_QUEST_MAP_SID    1040
#define IDC_EDIT_DIEMOB_NAME            1040
#define IDC_EDIT_START_QUEST_MAP_NAME   1041
#define IDC_EDIT_DIEMOB_NUM             1041
#define IDC_BUTTON_MAP_ADD              1042
#define IDC_EDIT_REACH_MAP_MID          1042
#define IDC_BUTTON_MAP_DEL              1043
#define IDC_EDIT_REACH_MAP_SID          1043
#define IDC_EDIT_START_QUEST_MAP_X      1044
#define IDC_EDIT_REACH_MAP_NAME         1044
#define IDC_EDIT_START_QUEST_MAP_Y      1045
#define IDC_EDIT_REACH_PX               1045
#define IDC_EDIT_START_QUEST_MAP_SIZE   1046
#define IDC_EDIT_REACH_PY               1046
#define IDC_COMBO_PROGRESS_START        1047
#define IDC_EDIT_REACH_RADIUS           1047
#define IDC_CHECK_PROGRESS_USE          1048
#define IDC_EDIT_GUARD_MAP_MID          1048
#define IDC_EDIT_GIFT_EXP               1049
#define IDC_EDIT_GUARD_MAP_SID          1049
#define IDC_EDIT_GIFT_MONEY             1050
#define IDC_EDIT_GUARD_MAP_NAME         1050
#define IDC_CHECK_FAIL_TIMEOVER         1051
#define IDC_EDIT_GUARD_PX               1051
#define IDC_CHECK_FAIL_DIE              1052
#define IDC_EDIT_GUARD_PY               1052
#define IDC_CHECK_FAIL_LEAVE            1053
#define IDC_EDIT_GUARD_RADIUS           1053
#define IDC_BUTTON_MAP_ADD_START        1054
#define IDC_EDIT_GUARD_TIME             1054
#define IDC_EDIT_MAP_MID_START          1055
#define IDC_STEP_MAP_MID_EDIT           1055
#define IDC_EDIT_MAP_SID_START          1056
#define IDC_STEP_MAP_SID_EDIT           1056
#define IDC_BUTTON_MAP_DEL_START        1057
#define IDC_STEP_MAP_NAME               1057
#define IDC_EDIT_MAP_NAME_START         1058
#define IDC_STEP_MAP_XPOS_EDIT          1058
#define IDC_BUTTON_ALL_MALE             1059
#define IDC_STEP_MAP_YPOS_EDIT          1059
#define IDC_EDIT_MAP_X_START            1060
#define IDC_STEP_MAP_GATE_EDIT          1060
#define IDC_EDIT_MAP_Y_START            1061
#define IDC_BUTTON_STEP_EDIT            1061
#define IDC_EDIT_MAP_GATE_START         1062
#define IDC_CHECK_REQ_CLASS_BRAWLER_M   1063
#define IDC_CHECK_REQ_CLASS_SWORDSMAN_M 1064
#define IDC_CHECK_REQ_CLASS_ARCHER_M    1065
#define IDC_CHECK_REQ_CLASS_SHAMAN_M    1066
#define IDC_CHECK_REQ_CLASS_EXTREME_M   1067
#define IDC_COMBO_PROGRESS_END          1068
#define IDC_BUTTON_MAP_ADD_END          1069
#define IDC_EDIT_MAP_MID_END            1070
#define IDC_EDIT_MAP_SID_END            1071
#define IDC_BUTTON_ALL_FEMALE           1072
#define IDC_BUTTON_ALL                  1073
#define IDC_BUTTON_NOTHING              1074
#define IDC_CHECK_REQ_CLASS_SWORDSMAN_F 1075
#define IDC_CHECK_REQ_CLASS_BRAWLER_F   1076
#define IDC_CHECK_REQ_CLASS_ARCHER_F    1077
#define IDC_CHECK_REQ_CLASS_SHAMAN_F    1078
#define IDC_CHECK_REQ_CLASS_EXTREME_F   1079
#define IDC_BUTTON_MAP_DEL_END          1080
#define IDC_EDIT_MAP_NAME_END           1081
#define IDC_EDIT_MAP_X_END              1082
#define IDC_EDIT_MAP_Y_END              1083
#define IDC_EDIT_MAP_GATE_END           1084
#define IDC_COMBO_PROGRESS_FAIL         1085
#define IDC_BUTTON_MAP_ADD_FAIL         1086
#define IDC_EDIT_MAP_MID_FAIL           1087
#define IDC_EDIT_MAP_SID_FAIL           1088
#define IDC_BUTTON_MAP_DEL_FAIL         1089
#define IDC_EDIT_MAP_NAME_FAIL          1090
#define IDC_EDIT_MAP_X_FAIL             1091
#define IDC_EDIT_MAP_Y_FAIL             1092
#define IDC_EDIT_MAP_GATE_FAIL          1093
#define IDC_EDIT_GIFT_SKILLP            1094
#define IDC_EDIT_GIFT_STATP             1095
#define IDC_EDIT_GIFT_ELEMENT           1096
#define IDC_EDIT_GIFT_LIFEP             1097
#define IDC_EDIT_GIFT_DISPK             1098
#define IDC_EDIT_GIFT_QUEST             1099
#define IDC_LIST_GIFT_ITEM              1100
#define IDC_BUTTON_GIFT_ITEM_ADD        1101
#define IDC_BUTTON_GIFT_ITEM_DEL        1102
#define IDC_BUTTON_GIFT_ITEM_EDIT       1103
#define IDC_EDIT_INSERT_MID_ITEM        1104
#define IDC_EDIT_INSERT_SID_ITEM        1105
#define IDC_BUTTON_GIFT_ITEM_INSERT     1106
#define IDC_LIST_GIFT_SKILL             1107
#define IDC_LIST_STEP                   1107
#define IDC_BUTTON_GIFT_SKILL_ADD       1108
#define IDC_EDIT_STEP_COMMENT           1108
#define IDC_BUTTON_GIFT_SKILL_DEL       1109
#define IDC_BUTTON_TALKNPC              1109
#define IDC_BUTTON_MAP_DEL_START2       1110
#define IDC_BUTTON_TALKNPC_DEL          1110
#define IDC_EDIT_INSERT_MID_SKILL       1111
#define IDC_BUTTON_GUARDNPC             1111
#define IDC_EDIT_INSERT_SID_SKILL       1112
#define IDC_BUTTON_GUARDNPC_DEL         1112
#define IDC_BUTTON_GIFT_SKILL_INSERT    1113
#define IDC_BUTTON_DIEMOB               1113
#define IDC_BUTTON_MAP_DEL_END2         1114
#define IDC_BUTTON_DIEMOB_DEL           1114
#define IDC_BUTTON_MAP_DEL_FAIL2        1115
#define IDC_BUTTON_REACH_MAP            1115
#define IDC_BUTTON_REACH_MAP_DEL        1116
#define IDC_CHECK_REQ_CLASS_EXTREME_M2  1116
#define IDC_CHECK_REQ_CLASS_GUNNER_M    1116
#define IDC_BUTTON_GUARD_MAP            1117
#define IDC_CHECK_REQ_CLASS_GUNNER_F    1117
#define IDC_BUTTON_GUARD_MAP_DEL        1118
#define IDC_CHECK_REQ_CLASS_ASSASSIN_M  1118
#define IDC_STEP_MAP_EDIT_BUTTON        1119
#define IDC_CHECK_REQ_CLASS_ASSASSIN_F  1119
#define IDC_STEP_MAP_EDIT_DEL           1120
#define IDC_CHECK_REQ_CLASS_TRICKER_M   1120
#define IDC_EDIT_LEVEL                  1121
#define IDC_CHECK_REQ_CLASS_TRICKER_F   1121
#define IDC_LIST_ITEM_GAIN              1122
#define IDC_COMBO_SCHOOL2               1122
#define IDC_COMBO_QUEST_AREA            1122
#define IDC_BUTTON_ITEM_ADD_GAIN        1123
#define IDC_BUTTON_ITEM_DEL_GAIN        1124
#define IDC_BUTTON_ITEM_EDIT_GAIN       1125
#define IDC_COMBO_SEARCH                1125
#define IDC_BUTTON_ITEM_INSERT_GAIN     1126
#define IDC_EDIT_INSERT_MID_GAIN        1127
#define IDC_EDIT_INSERT_SID_GAIN        1128
#define IDC_BUTTON_GEN_MOB_DEL          1128
#define IDC_LIST_ITEM_REMOVE            1129
#define IDC_BUTTON_ITEM_ADD_REMOVE      1130
#define IDC_EDIT_GEN_RATE               1130
#define IDC_BUTTON_ITEM_DEL_REMOVE      1131
#define IDC_BUTTON_GEN_MOB_INSERT       1131
#define IDC_EDIT_INSERT_MID             1132
#define IDC_BUTTON_ITEM_INSERT_REMOVE   1133
#define IDC_EDIT_INSERT_SID             1133
#define IDC_EDIT_INSERT_MID_DEL         1134
#define IDC_LIST_GEN_MOB                1134
#define IDC_EDIT_INSERT_SID_DEL         1135
#define IDC_LIST_ITEM_GEN               1136
#define IDC_BUTTON_ITEM_ADD_GEN         1137
#define IDC_BUTTON_ITEM_DEL_GEN         1138
#define IDC_BUTTON_ITEM_EDIT_GEN        1139
#define IDC_BUTTON_ITEM_INSERT_GEN      1140
#define IDC_EDIT_INSERT_MID_GEN         1141
#define IDC_EDIT_INSERT_SID_GEN         1142
#define IDC_STATIC_TITLE                1143
#define IDC_STATIC_DESC                 1144
#define IDC_STATIC_TALKNPC              1145
#define IDC_STATIC_DEFENDNPC            1146
#define IDC_STATIC_REACHLEVEL           1147
#define IDC_STATIC_REACHLEVEL2          1148
#define IDC_STATIC_KILLMOB              1149
#define IDC_STATIC_KILLMOB2             1150
#define IDC_STATIC_MOVEMAP              1151
#define IDC_STATIC_MOVEMAP2             1152
#define IDC_STATIC_MOVEMAP3             1153
#define IDC_STATIC_REACHMAP             1154
#define IDC_STATIC_REACHMAP2            1155
#define IDC_STATIC_REACHMAP3            1156
#define IDC_STATIC_DEFENDMAP            1157
#define IDC_STATIC_DEFENDMAP1           1158
#define IDC_STATIC_DEFENDMAP2           1159
#define IDC_STATIC_DEFENDMAP3           1160
#define IDC_STATIC_ITEMGAIN             1161
#define IDC_STATIC_ITEMGAIN2            1162
#define IDC_STATIC_ITEMDEL              1163
#define IDC_STATIC_ITEMDEL2             1164
#define IDC_STATIC_ITEMGEN              1165
#define IDC_STATIC_ITEMGEN2             1166
#define IDC_BUTTON_STEP_OK              1167
#define IDC_BUTTON_STEP_OK2             1168
#define IDC_BUTTON_STEP_CANCEL          1168
#define ID_FILE_ADD                     32771
#define ID_FILE_DEL                     32772
#define ID_FILE_COPY                    32773
#define ID_FILE_PASTE                   32774
#define ID_FILE_PASTEVALUE              32775
#define ID_FILE_QUESTEDIT               32776
#define ID_FILE_QUESTSTEPEDIT           32777

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1168
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
