//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EditorItem.rc
//
#define ID_LOAD_ITEM                    3
#define ID_ADDCOLOUR                    3
#define ID_SAVE_ITEM                    4
#define ID_LOAD_CSV                     5
#define ID_SAVE_CSV                     6
#define ID_SEARCH                       7
#define ID_LOAD_CSV_ROPT                8
#define ID_SAVE_CSV2                    9
#define ID_SAVE_CSV_ROPT                9
#define IDD_EDITORITEM_DIALOG           102
#define IDD_EDIT1                       103
#define IDD_EDIT2                       104
#define IDD_TREE                        105
#define IDR_MAINFRAME                   128
#define IDR_MENU_EDIT                   129
#define IDD_DIALOG_ITEMBOX              129
#define IDD_DIALOG_SEARCH               130
#define IDD_DIALOG_ITEMBOXR             131
#define IDD_DIALOG_MOB                  132
#define IDD_DIALOG_CROW                 133
#define IDD_DIALOG_SKILL                134
#define IDD_DIALOG_CROW1                135
#define IDD_DIALOG_MAP                  135
#define IDD_DLG_COLOR                   136
#define IDD_DIALOG_ITEM                 137
#define IDC_DRAGITEM                    310
#define IDC_STATIC_TOOL                 1000
#define IDC_STATIC_BLOW_OPTION1         1001
#define IDC_STATIC_BLOW_OPTION2         1002
#define IDC_BUTTON_PAGE_NEXT            1003
#define IDC_BUTTON_PAGE_BACK            1003
#define IDC_HUE                         1003
#define IDC_STATIC_QUESTION_OPTION2     1004
#define IDC_SAT                         1004
#define IDC_TREE                        1005
#define IDC_BUTTON_SEARCH               1005
#define IDC_STATIC_QUESTION_OPTION3     1005
#define IDC_LUM                         1005
#define IDC_STATIC_QUESTION_OPTION1     1006
#define IDC_RED                         1006
#define IDC_CHECK_DRUG_RATIO            1007
#define IDC_GREEN                       1007
#define IDC_LIST_RESULT                 1008
#define IDC_CHECK_CURE_NUMB             1008
#define IDC_BLUE                        1008
#define IDC_CHECK_CURE_STUN             1009
#define IDC_COMBO_SEARCHTYPE            1010
#define IDC_CHECK_CURE_STONE            1010
#define IDC_COMBO_ITEM_TYPE             1011
#define IDC_CHECK_CURE_FROZEN           1011
#define IDC_CHECK_CURE_MAD              1012
#define IDC_REF                         1012
#define IDC_EDIT_SEARCH                 1013
#define IDC_CHECK_CURE_POISON           1013
#define IDC_BUTTON_GO                   1014
#define IDC_CHECK_CURE_CURSE            1014
#define IDC_EDIT_X                      1015
#define IDC_CHECK_CURE_BURN             1015
#define IDC_EDIT_Y                      1016
#define IDC_LIST_PETSKIN                1016
#define IDC_LIST_BOX                    1017
#define IDC_BUTTON_BOX_ADD              1018
#define IDC_LIST_BOX3                   1018
#define IDC_BUTTON_BOX_DEL              1019
#define IDC_BUTTON_INSERT               1019
#define IDC_EDIT_GROUP_MID              1020
#define IDC_BUTTON_BOX_UP               1020
#define IDC_BUTTON_REMOVE               1020
#define IDC_EDIT_GROUP_SID              1021
#define IDC_BUTTON_BOX_DOWN             1021
#define IDC_EDIT_SEL_MID                1021
#define IDC_EDIT_ITEMID_MID             1022
#define IDC_BUTTON_BOX_INSERT           1022
#define IDC_EDIT_SEL_SID                1022
#define IDC_EDIT_ITEMID_SID             1023
#define IDC_LIST_BOX2                   1023
#define IDC_EDIT_SEL_NAME               1023
#define IDC_EDIT_NAME                   1024
#define IDC_BUTTON_BOX_ADD2             1024
#define IDC_EDIT_SEL_NUM                1024
#define IDC_EDIT_NAME2                  1025
#define IDC_BUTTON_BOX_DEL2             1025
#define IDC_LIST_SELECT                 1025
#define IDC_EDIT_COMMENT                1026
#define IDC_BUTTON_BOX_UP2              1026
#define IDC_LIST_SELECTED               1026
#define IDC_EDIT_COMMENT2               1027
#define IDC_BUTTON_BOX_DOWN2            1027
#define IDC_COMBO_GRADE                 1028
#define IDC_BUTTON_BOX_INSERT2          1028
#define IDC_EDIT_SEL_RATE               1028
#define IDC_COMBO_ITEMTYPE              1029
#define IDC_BUTTON_PS_ADD               1029
#define IDC_EDIT_SEL_SCALE              1029
#define IDC_EDIT_PRICE_BUY              1030
#define IDC_BUTTON_PS_DEL               1030
#define IDC_STATIC_SEARCH_1             1030
#define IDC_EDIT_PRICE_SELL             1031
#define IDC_BUTTON_PS_INSERT            1031
#define IDC_STATIC_SEARCH_2             1031
#define IDC_CHECK_FLAG_SALE             1032
#define IDC_STATIC_SEARCH_3             1032
#define IDC_LIST_RVCARD                 1032
#define IDC_CHECK_FLAG_EXCHANGE         1033
#define IDC_CHECK1                      1033
#define IDC_CHECK_RVCARD_CHECK_EXIST    1033
#define IDC_CHECK_FLAG_THROW            1034
#define IDC_CHECK_RVCARD_REPLACE_VALUE  1034
#define IDC_CHECK_FLAG_DISGUISE         1035
#define IDC_BUTTON_RVCARD_DEL           1035
#define IDC_CHECK_FLAG_TIMELMT          1036
#define IDC_BUTTON_RVCARD_SET           1036
#define IDC_CHECK_FLAG_GARBAGE          1037
#define IDC_CHECK_FLAG_EVENTITEM        1038
#define IDC_CHECK_FLAG_CHANNELALL       1039
#define IDC_EDIT_EXPIRY_D               1040
#define IDC_EDIT_GEN_SPECID             1041
#define IDC_EDIT_EXPIRY_H               1042
#define IDC_EDIT_REQ_POW                1043
#define IDC_EDIT_EXPIRY_M               1044
#define IDC_CHECK_REQ_SCHOOL_SG         1045
#define IDC_EDIT_GEN_LIMITTIME          1046
#define IDC_EDIT_GRADE_DEF              1046
#define IDC_EDIT_GEN_LIMITTIMEGEN       1047
#define IDC_EDIT_GRADE_ATT              1047
#define IDC_CHECK_CONSUMABLE            1048
#define IDC_EDIT_EXPMULTIPLE            1048
#define IDC_COMBO_BRIGHT                1049
#define IDC_EDIT_REMODEL                1049
#define IDC_EDIT_REQ_DEX                1050
#define IDC_EDIT_REMODEL2               1050
#define IDC_EDIT_GRIND_STRING           1050
#define IDC_EDIT_REQ_SPI                1051
#define IDC_EDIT_REQ_STA                1052
#define IDC_EDIT_REQ_STR                1053
#define IDC_EDIT_REQ_INT                1054
#define IDC_EDIT_REQ_SA                 1055
#define IDC_EDIT_REQ_PA                 1056
#define IDC_EDIT_REQ_LEVEL_MIN          1057
#define IDC_EDIT_REQ_LEVEL_MAX          1058
#define IDC_BUTTON_ALL_MALE             1059
#define IDC_COMBO_COOLDOWN_TYPE         1060
#define IDC_CHECK_REQ_SCHOOL_MP         1061
#define IDC_CHECK_REQ_SCHOOL_PHX        1062
#define IDC_CHECK_REQ_CLASS_BRAWLER_M   1063
#define IDC_CHECK_REQ_CLASS_SWORDSMAN_M 1064
#define IDC_CHECK_REQ_CLASS_ARCHER_M    1065
#define IDC_CHECK_REQ_CLASS_SHAMAN_M    1066
#define IDC_CHECK_REQ_CLASS_EXTREME_M   1067
#define IDC_EDIT_EFFECT_SELFBODY        1068
#define IDC_EDIT_COOLDOWN_VALUE         1069
#define IDC_BUTTON_SELFBODY             1070
#define IDC_BUTTON_PAGE_CANCEL          1071
#define IDC_BUTTON_ALL_FEMALE           1072
#define IDC_BUTTON_ALL                  1073
#define IDC_BUTTON_NOTHING              1074
#define IDC_CHECK_REQ_CLASS_SWORDSMAN_F 1075
#define IDC_CHECK_REQ_CLASS_BRAWLER_F   1076
#define IDC_CHECK_REQ_CLASS_ARCHER_F    1077
#define IDC_CHECK_REQ_CLASS_SHAMAN_F    1078
#define IDC_CHECK_REQ_CLASS_EXTREME_F   1079
#define IDC_EDIT_EFFECT_TARGETBODY      1080
#define IDC_EDIT_EFFECT_TARGET          1081
#define IDC_EDIT_PETWEAR                1082
#define IDC_EDIT_RANDOM_OPTION          1083
#define IDC_BUTTON_SHAPEFIELD           1084
#define IDC_EDIT_INVENTORY              1085
#define IDC_EDIT_FIELD                  1086
#define IDC_EDIT_WEAR_BRAWLER_F         1087
#define IDC_EDIT_WEAR_SWORDSMAN_F       1088
#define IDC_EDIT_WEAR_ARCHER_F          1089
#define IDC_EDIT_WEAR_SHAMAN_F          1090
#define IDC_BUTTON_PAGE_SAVE            1091
#define IDC_CHECK_HAND_TWO              1092
#define IDC_COMBO_PET                   1092
#define IDC_CHECK_HAND_BIG              1093
#define IDC_EDIT_PET_MID                1093
#define IDC_CHECK_HAND_BROOM            1094
#define IDC_EDIT_PET_SID                1094
#define IDC_EDIT_WEAR_EXTREME_F         1095
#define IDC_RADIO_HAND_R                1095
#define IDC_RADIO_HAND_L                1096
#define IDC_COMBO_VEHICLE               1096
#define IDC_RADIO_HAND_BOTH             1097
#define IDC_EDIT_SKILL_MID              1097
#define IDC_COMBO_SUIT                  1098
#define IDC_EDIT_SKILL_SID              1098
#define IDC_COMBO_ATTACK                1099
#define IDC_EDIT_MAP_MID                1099
#define IDC_EDIT_STAT_DAMAGE_MIN        1100
#define IDC_EDIT_MAP_SID                1100
#define IDC_EDIT_STAT_DAMAGE_MAX        1101
#define IDC_EDIT_MAP_POSX               1101
#define IDC_EDIT_STAT_DEFENSE           1102
#define IDC_EDIT_MAP_POSY               1102
#define IDC_EDIT_STAT_HITRATE           1103
#define IDC_STATIC_10                   1103
#define IDC_EDIT_STAT_AVOIDRATE         1104
#define IDC_STATIC_20                   1104
#define IDC_EDIT_MAP_MID2               1104
#define IDC_EDIT_STAT_SPUSAGE           1105
#define IDC_STATIC_3                    1105
#define IDC_STATIC_30                   1105
#define IDC_EDIT_STAT_WEAPONRANGE       1106
#define IDC_BUTTON_PET_CROW_ADD         1106
#define IDC_EDIT_APPLY_F                1107
#define IDC_EDIT_RES_FIRE               1107
#define IDC_BUTTON_BRAWLER_F            1108
#define IDC_EDIT_RES_SPIRIT             1108
#define IDC_BUTTON_SWORDSMAN_F          1109
#define IDC_EDIT_RES_POISON             1109
#define IDC_BUTTON_ARCHER_F             1110
#define IDC_EDIT_RES_ICE                1110
#define IDC_BUTTON_SHAMAN_F             1111
#define IDC_EDIT_RES_ELECT              1111
#define IDC_BUTTON_EXTREME_F            1112
#define IDC_COMBO_UPGRADE_TYPE          1112
#define IDC_COMBO_UPGRADE_LEVEL         1113
#define IDC_BUTTON_SKILL_SCROLL_ADD     1113
#define IDC_COMBO_UPGRADE_CLASS         1114
#define IDC_BUTTON_PET_CROW_CHECK       1114
#define IDC_CHECK_REQ_CLASS_GUNNER_M    1114
#define IDC_COMBO_ADDON_00              1115
#define IDC_BUTTON_SKILL_SCROLL_CHECK   1115
#define IDC_CHECK_REQ_CLASS_EXTREME_F2  1115
#define IDC_CHECK_REQ_CLASS_GUNNER_F    1115
#define IDC_BUTTON_APPLY_F              1116
#define IDC_COMBO_ADDON_01              1116
#define IDC_BUTTON_CLEAR_F              1117
#define IDC_COMBO_ADDON_02              1117
#define IDC_EDIT_WEAR_BRAWLER_M         1118
#define IDC_COMBO_ADDON_03              1118
#define IDC_EDIT_WEAR_SWORDSMAN_M       1119
#define IDC_EDIT_ADDON_00               1119
#define IDC_EDIT_WEAR_ARCHER_M          1120
#define IDC_EDIT_ADDON_01               1120
#define IDC_EDIT_WEAR_SHAMAN_M          1121
#define IDC_EDIT_ADDON_02               1121
#define IDC_EDIT_WEAR_EXTREME_M         1122
#define IDC_EDIT_ADDON_03               1122
#define IDC_COMBO_ITEM_VAR_VAR          1123
#define IDC_EDIT_PET_NAME               1123
#define IDC_COMBO_DRUG_TYPE             1124
#define IDC_EDIT_SKILL_NAME             1124
#define IDC_EDIT_VALUE_VAR              1125
#define IDC_BUTTON_SPECMAP_ADD          1125
#define IDC_COMBO_SEARCH                1125
#define IDC_EDIT_APPLY_M                1126
#define IDC_COMBO_ITEM_VAR_VOL          1126
#define IDC_BUTTON1                     1126
#define IDC_BUTTON_BRAWLER_M            1127
#define IDC_EDIT_VALUE_VOL              1127
#define IDC_BUTTON_SWORDSMAN_M          1128
#define IDC_COMBO_BLOW_TYPE             1128
#define IDC_BUTTON_ARCHER_M             1129
#define IDC_EDIT_BLOW_TIME              1129
#define IDC_BUTTON_SHAMAN_M             1130
#define IDC_EDIT_BLOW_CHANCE            1130
#define IDC_BUTTON_EXTREME_M            1131
#define IDC_EDIT_BLOW_VAR1              1131
#define IDC_EDIT_BLOW_VAR2              1132
#define IDC_BUTTON_NPCREC_ADD           1132
#define IDC_COMBO_QUESTION_TYPE         1133
#define IDC_BUTTON_SPECMAP_CHECK        1133
#define IDC_COMBO_VEHICLE2              1133
#define IDC_EDIT_QUESTION_TIME          1134
#define IDC_BUTTON_NPCREC_CHECK         1134
#define IDC_CHECK_VEHICLE_NOACC         1134
#define IDC_BUTTON_APPLY_M              1135
#define IDC_EDIT_QUESTION_VAR1          1135
#define IDC_BUTTON_CLEAR_M              1136
#define IDC_EDIT_QUESTION_VAR2          1136
#define IDC_EDIT_QUESTION_VAR3          1137
#define IDC_EDIT_MAP_SID2               1137
#define IDC_EDIT_DRUG_VOLUME            1138
#define IDC_EDIT_PET_NAME2              1138
#define IDC_EDIT_MAP_NAME               1138
#define IDC_EDIT_DRUG_PILE              1139
#define IDC_EDIT_MAP_NAME2              1139
#define IDC_EDIT_BOX_MID                1140
#define IDC_STATIC_11                   1140
#define IDC_EDIT_BOX_SID                1141
#define IDC_EDIT_WEAR_GUNNER_F          1141
#define IDC_EDIT_BOX_SID2               1142
#define IDC_BUTTON_GUNNER_F             1142
#define IDC_EDIT_BOX_NUM                1143
#define IDC_EDIT_WEAR_GUNNER_M          1143
#define IDC_EDIT_BOX2_MID               1144
#define IDC_BUTTON_GUNNER_M             1144
#define IDC_EDIT_BOX2_SID               1145
#define IDC_CHECK_REQ_CLASS_ASSASSIN_M  1145
#define IDC_EDIT_PS_MID                 1146
#define IDC_CHECK_REQ_CLASS_ASSASSIN_F  1146
#define IDC_EDIT_BOX2_RATE              1147
#define IDC_CHECK_REQ_CLASS_TRICKER_M   1147
#define IDC_EDIT_PS_SID                 1148
#define IDC_EDIT_WEAR_BRAWLER_F2        1148
#define IDC_EDIT_PS_RATE                1149
#define IDC_EDIT_WEAR_SWORDSMAN_F2      1149
#define IDC_EDIT_PS_SCALE               1150
#define IDC_EDIT_WEAR_ARCHER_F2         1150
#define IDC_EDIT_PS_TIME                1151
#define IDC_EDIT_WEAR_SHAMAN_F2         1151
#define IDC_EDIT_WEAR_EXTREME_F2        1152
#define IDC_COMBO_RVCARD_TYPE           1152
#define IDC_EDIT_APPLY_F2               1153
#define IDC_EDIT_RVCARD_VALUE           1153
#define IDC_BUTTON_BRAWLER_F2           1154
#define IDC_CHECK2                      1154
#define IDC_CHECK_GRIND_NOFAIL          1154
#define IDC_BUTTON_SWORDSMAN_F2         1155
#define IDC_STATIC_12                   1155
#define IDC_BUTTON_ARCHER_F2            1156
#define IDC_BUTTON_WRAPPER_BOX          1156
#define IDC_BUTTON_SHAMAN_F2            1157
#define IDC_EDIT_WRAPPER_BOX_MID        1157
#define IDC_BUTTON_EXTREME_F2           1158
#define IDC_EDIT_WRAPPER_BOX_SID        1158
#define IDC_BUTTON_APPLY_F2             1159
#define IDC_EDIT_MAP_NAME3              1159
#define IDC_EDIT_WRAPPER_BOX_NAME       1159
#define IDC_BUTTON_CLEAR_F2             1160
#define IDC_EDIT_WEAR_BRAWLER_M2        1161
#define IDC_EDIT_WEAR_SWORDSMAN_M2      1162
#define IDC_EDIT_WEAR_ARCHER_M2         1163
#define IDC_EDIT_WEAR_SHAMAN_M2         1164
#define IDC_EDIT_WEAR_EXTREME_M2        1165
#define IDC_EDIT_APPLY_M2               1166
#define IDC_BUTTON_BRAWLER_M2           1167
#define IDC_BUTTON_SWORDSMAN_M2         1168
#define IDC_BUTTON_ARCHER_M2            1169
#define IDC_BUTTON_SHAMAN_M2            1170
#define IDC_BUTTON_EXTREME_M2           1171
#define IDC_BUTTON_APPLY_M2             1172
#define IDC_BUTTON_CLEAR_M2             1173
#define IDC_EDIT_WEAR_GUNNER_F2         1174
#define IDC_BUTTON_TARGET_BODY          1175
#define IDC_BUTTON_PARTNEREFFECT        1176
#define IDC_BUTTON_GUNNER_F2            1177
#define IDC_BUTTON_PETWEAR              1178
#define IDC_BUTTON_RANDOMOPTION         1179
#define IDC_BUTTON_SHAPEINVEN           1180
#define IDC_EDIT_INVEN_SIZE_X           1181
#define IDC_EDIT_INVEN_SIZE_Y           1182
#define IDC_EDIT_ICON_MID               1183
#define IDC_EDIT_ICON_SID               1184
#define IDC_EDIT_WEAR_GUNNER_M2         1185
#define IDC_BUTTON_GUNNER_M2            1186
#define IDC_CHECK_REQ_CLASS_TRICKER_F   1187
#define IDC_EDIT_WEAR_ASSASSIN_F        1188
#define IDC_BUTTON_ASSASSIN_F           1189
#define IDC_EDIT_WEAR_ASSASSIN_M        1190
#define IDC_BUTTON_ASSASSIN_M           1191
#define IDC_EDIT_WEAR_TRICKER_F         1192
#define IDC_BUTTON_TRICKER_F            1193
#define IDC_EDIT_WEAR_TRICKER_M         1194
#define IDC_BUTTON_TRICKER_M            1195
#define IDC_EDIT_WEAR_ASSASSIN_F2       1196
#define IDC_BUTTON_ASSASSIN_F2          1197
#define IDC_EDIT_WEAR_ASSASSIN_M2       1198
#define IDC_BUTTON_ASSASSIN_M2          1199
#define IDC_EDIT_WEAR_TRICKER_F2        1200
#define IDC_BUTTON_TRICKER_F2           1201
#define IDC_EDIT_WEAR_TRICKER_M2        1202
#define IDC_BUTTON_TRICKER_M2           1203
#define IDC_EDIT_EXDATA_1_0             1204
#define IDC_COMBO_COOLDOWN_TYPE2        1204
#define IDC_COMBO_ACTIVITY_REQ_TYPE     1204
#define IDC_CHECK_FLAG_TIMELMT2         1204
#define IDC_CHECK_ENABLE_SPEC           1204
#define IDC_EDIT_EXDATA_1_1             1205
#define IDC_EDIT_ACTIVITY_POINT_REQ     1205
#define IDC_EDIT_EXDATA_1_2             1206
#define IDC_EDIT_CONTRIBUTION_POINT_REQ 1206
#define IDC_CHECK_FLAG_EX_1             1207
#define IDC_CHECK_FLAG_EX_2             1208
#define IDC_CHECK_FLAG_EX_3             1209
#define IDC_CHECK_FLAG_EX_4             1210
#define IDC_EDIT_REQ_SPI2               1211
#define IDC_EDIT_REQ_USERNUM            1211
#define IDC_CHECK_FLAG_EX_5             1212
#define IDC_EDIT_VEHICLE_COLOR_1        1213
#define IDC_EDIT_VEHICLE_COLOR_2        1214
#define IDC_BUTTON_VEHICLE_DEFAULT_COLOR_1 1215
#define IDC_BUTTON_VEHICLE_DEFAULT_COLOR_2 1216
#define IDC_EDIT_SUIT_DUMMY_1           1217
#define IDC_EDIT_SUIT_DUMMY_2           1218
#define IDC_EDIT_SUIT_DUMMY_3           1219
#define IDC_ITEM_COLOR_USE              1220
#define IDC_EDIT_ITEM_COLOR_1           1221
#define IDC_EDIT_VEHICLE_COLOR_4        1222
#define IDC_EDIT_ITEM_COLOR_2           1222
#define IDC_BUTTON_ITEM_DEFAULT_COLOR_1 1223
#define IDC_BUTTON_ITEM_DEFAULT_COLOR_2 1224
#define IDC_CHECK_FLAG_CHANNELALL2      1225
#define IDC_CHECK_ITEM_TRANSFER         1225
#define ID_TOOL_ADD                     32771
#define ID_TOOL_DELETE                  32773
#define ID_TOOL_COPY                    32774
#define ID_TOOL_PASTE_VAL               32777
#define ID_TOOL_PASTE_NEW               32778
#define ID_TOOL_EDIT1                   32779
#define ID_TOOL_EDIT2                   32781

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1155
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
