//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EditorSkinChar.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_EditorSkinCharTYPE          130
#define IDD_DLG_MAIN                    310
#define IDD_PAGE_CHF                    311
#define IDD_PAGE_ABF                    312
#define IDD_PAGE_ABL                    313
#define IDD_PAGE_CHF1                   314
#define IDD_PAGE_VCF                    314
#define IDD_DLG_ANI_SELECT              315
#define IDC_STATIC_TOOL                 1000
#define IDC_BUTTON_CHF_LOAD             1000
#define IDC_BUTTON_CHF_SAVE             1001
#define IDC_EDIT_CHF_FILENAME           1002
#define IDC_BUTTON_CHF_NEW              1003
#define IDC_ABL_EDIT_SKELETON           1003
#define IDC_BUTTON_CHF_TEST             1004
#define IDC_ABL_BUTTON_SKELETON         1004
#define IDC_BUTTON_CHF_PIECE_CPS        1005
#define IDC_ABL_EDIT_MASKP              1005
#define IDC_BUTTON_CHF_PIECE_RESET      1006
#define IDC_ABL_COMBO_STRIKE            1006
#define IDC_BUTTON_CHF_ANIM_PLAY        1007
#define IDC_ABL_COMBO_PTYPE             1007
#define IDC_BUTTON_CHF_ANIM_DELETE      1008
#define IDC_ABL_COMBO_SLOTB             1008
#define IDC_BUTTON_CHF_ANIM_CLEAR       1009
#define IDC_ABL_BUTTON_MASKP            1009
#define IDC_BUTTON_CHF_ANIM_ADDCFG      1010
#define IDC_ABL_EDIT_BONEDATA           1010
#define IDC_BUTTON_CHF_ANIM_STOP        1011
#define IDC_ABL_BUTTON_BONEDATA         1011
#define IDC_BUTTON_CHF_SKELETON         1012
#define IDC_ABL_EDIT_BONELINK           1012
#define IDC_EDIT_CHF_SKELETON           1013
#define IDC_ABL_BUTTON_BONELINK         1013
#define IDC_EDIT_CHF_SCALE              1014
#define IDC_ABL_BUTTON_EDITMAT_1        1014
#define IDC_EDIT_CHF_HEIGHT             1015
#define IDC_ABL_BUTTON_EDITMAT_2        1015
#define IDC_LIST_CHF_ANIM               1016
#define IDC_ABL_BUTTON_RESET_MAT01      1016
#define IDC_LIST_CHF_PIECE              1017
#define IDC_ABL_BUTTON_MASKP_RESET      1017
#define IDC_EDIT_CHF_RADIUS             1018
#define IDC_ABL_BUTTON_RESET_MAT02      1018
#define IDC_BUTTON_CHF_APPLY            1019
#define IDC_ABL_BUTTON_ANIM_PLAY        1019
#define IDC_CHECK1                      1020
#define IDC_CHECK_CHF_WORLDOBJECT       1020
#define IDC_ABL_BUTTON_ANIM_STOP        1020
#define IDC_LIST_ABF_PIECE              1021
#define IDC_BUTTON_CHF_PIECE_CPS2       1021
#define IDC_BUTTON_CHF_PIECE_ABL        1021
#define IDC_ABL_BUTTON_MANUAL_MAT1      1021
#define IDC_LIST_ABF_ANIM               1022
#define IDC_ABL_BUTTON_TEST_MAT_1       1022
#define IDC_BUTTON_CHF_PIECE_ABL2       1022
#define IDC_BUTTON_CHF_PIECE_VCF        1022
#define IDC_BUTTON_ABF_SKELETON         1023
#define IDC_ABL_BUTTON_SAVE_MAT_1       1023
#define IDC_EDIT_ABF_SKELETON           1024
#define IDC_ABL_BUTTON_CANCEL_MAT_1     1024
#define IDC_EDIT_ABF_SCALE              1025
#define IDC_ABL_BUTTON_MANUAL_MAT2      1025
#define IDC_EDIT_ABF_HEIGHT             1026
#define IDC_ABL_BUTTON_TEST_MAT_2       1026
#define IDC_EDIT_ABF_RADIUS             1027
#define IDC_ABL_BUTTON_SAVE_MAT_2       1027
#define IDC_CHECK_ABF_WORLDOBJECT       1028
#define IDC_ABL_BUTTON_CANCEL_MAT_2     1028
#define IDC_BUTTON_ABF_APPLY            1029
#define IDC_BUTTON_ABF_NEW              1030
#define IDC_BUTTON_ABF_LOAD             1031
#define IDC_BUTTON_ABF_SAVE             1032
#define IDC_BUTTON_ABF_PIECE_CPS        1033
#define IDC_BUTTON_ABF_PIECE_RESET      1034
#define IDC_BUTTON_ABF_ANIM_PLAY        1035
#define IDC_BUTTON_ABF_ANIM_STOP        1036
#define IDC_BUTTON_ABF_ANIM_ADDCFG      1037
#define IDC_BUTTON_ABF_ANIM_DELETE      1038
#define IDC_BUTTON_ABF_ANIM_CLEAR       1039
#define IDC_EDIT_ABF_FILENAME           1040
#define IDC_BUTTON_ABL_NEW              1041
#define IDC_EDIT_ANI_INSERT_ABF         1041
#define IDC_BUTTON_ABL_LOAD             1042
#define IDC_BUTTON_ABF_ANIM_CLEAR2      1042
#define IDC_BUTTON_ANI_INSERT_ABF       1042
#define IDC_BUTTON_ABL_SAVE             1043
#define IDC_EDIT_ABL_FILENAME           1044
#define IDC_EDIT_ANI_INSERT_CHF         1046
#define IDC_BUTTON_VCF_NEW              1046
#define IDC_BUTTON_ANI_INSERT_CHF       1047
#define IDC_BUTTON_VCF_LOAD             1047
#define IDC_BUTTON_VCF_SAVE             1048
#define IDC_EDIT_VCF_FILENAME           1049
#define IDC_BUTTON_VCF_SKELETON         1050
#define IDC_EDIT_VCF_SKELETON           1051
#define IDC_EDIT_VCF_SCALE              1052
#define IDC_EDIT_VCF_HEIGHT             1053
#define IDC_EDIT_VCF_RADIUS             1054
#define IDC_CHECK_VCF_WORLDOBJECT       1055
#define IDC_BUTTON_VCF_APPLY            1056
#define IDC_LIST_VCF_PIECE              1057
#define IDC_LIST_VCF_ANIM               1058
#define IDC_BUTTON_VCF_PIECE_CPS        1059
#define IDC_BUTTON_VCF_PIECE_RESET      1060
#define IDC_BUTTON_VCF_ANIM_PLAY        1061
#define IDC_BUTTON_VCF_ANIM_STOP        1062
#define IDC_BUTTON_VCF_ANIM_ADDCFG      1063
#define IDC_BUTTON_VCF_ANIM_DELETE      1064
#define IDC_BUTTON_VCF_ANIM_CLEAR       1065
#define IDC_VCF_EDIT_BONE_1             1066
#define IDC_VCF_BUTTON_BONE_1           1067
#define IDC_VCF_BUTTON_EDITMAT_1        1068
#define IDC_VCF_BUTTON_RESET_MAT_1      1069
#define IDC_VCF_BUTTON_BONE_2           1070
#define IDC_LIST_SELECT_ANIM            1070
#define IDC_EDIT_MATRIX_TRANS_X_1       1071
#define IDC_VCF_EDIT_BONE_2             1071
#define IDC_EDIT_MATRIX_TRANS_Y_1       1072
#define IDC_VCF_BUTTON_EDITMAT_2        1072
#define IDC_EDIT_MATRIX_TRANS_Z_1       1073
#define IDC_VCF_BUTTON_RESET_MAT_2      1073
#define IDC_EDIT_MATRIX_ROTATE_X_1      1074
#define IDC_BUTTON_VCF_TEST_SKIN        1074
#define IDC_EDIT_MATRIX_ROTATE_Y_1      1075
#define IDC_BUTTON_VCF_TEST_SKIN_P      1075
#define IDC_EDIT_MATRIX_ROTATE_Z_1      1076
#define IDC_BUTTON_VCF_TEST_SKIN_S      1076
#define IDC_EDIT_MATRIX_SCALE_X_1       1077
#define IDC_EDIT_ANI_INSERT_VCF         1077
#define IDC_EDIT_MATRIX_SCALE_Y_1       1078
#define IDC_BUTTON_ANI_INSERT_VCF       1078
#define IDC_EDIT_MATRIX_SCALE_Z_1       1079
#define IDC_EDIT_MATRIX_TRANS_X_VCF_1   1079
#define IDC_EDIT_MATRIX_TRANS_X_2       1080
#define IDC_EDIT_MATRIX_TRANS_Y_VCF_1   1080
#define IDC_EDIT_MATRIX_TRANS_Y_2       1081
#define IDC_EDIT_MATRIX_TRANS_Z_VCF_1   1081
#define IDC_EDIT_MATRIX_TRANS_Z_2       1082
#define IDC_EDIT_MATRIX_ROTATE_X_VCF_1  1082
#define IDC_EDIT_MATRIX_ROTATE_X_2      1083
#define IDC_EDIT_MATRIX_ROTATE_Y_VCF_1  1083
#define IDC_EDIT_MATRIX_ROTATE_Y_2      1084
#define IDC_EDIT_MATRIX_ROTATE_Z_VCF_1  1084
#define IDC_EDIT_MATRIX_ROTATE_Z_2      1085
#define IDC_EDIT_MATRIX_SCALE_X_2       1086
#define IDC_EDIT_MATRIX_TRANS_X_VCF_2   1086
#define IDC_EDIT_MATRIX_SCALE_Y_2       1087
#define IDC_EDIT_MATRIX_TRANS_Y_VCF_2   1087
#define IDC_EDIT_MATRIX_SCALE_Z_2       1088
#define IDC_EDIT_MATRIX_TRANS_Z_VCF_2   1088
#define IDC_EDIT_MATRIX_ROTATE_X_VCF_2  1089
#define IDC_EDIT_MATRIX_ROTATE_Y_VCF_2  1090
#define IDC_EDIT_MATRIX_ROTATE_Z_VCF_2  1091
#define IDC_VCF_BUTTON_MANUAL_MAT1      1095
#define IDC_VCF_BUTTON_MANUAL_MAT2      1096
#define IDC_VCF_BUTTON_TEST_MAT_1       1097
#define IDC_VCF_BUTTON_SAVE_MAT_1       1098
#define IDC_VCF_BUTTON_CANCEL_MAT_1     1099
#define IDC_VCF_BUTTON_TEST_MAT_2       1100
#define IDC_VCF_BUTTON_SAVE_MAT_2       1101
#define IDC_VCF_BUTTON_CANCEL_MAT_2     1102
#define ID_VIEW_EDITORTOOLBAR           32771
#define ID_RENDER_DEBUGINFO             32772
#define ID_RENDER_RENDERPLANE           32773
#define ID_RENDER_PLANE                 32774
#define ID_RENDER_RENDERAABBBOX         32775
#define ID_RENDER_AABBBOX               32776
#define ID_RENDER_RENDERSKELETON        32777
#define ID_RENDER_SKELETON              32778
#define ID_RENDER_ATTACKSTANCE          32779
#define ID_RENDER_RESETCAMERA           32780
#define ID_ITEMLEVEL_OFF                32781
#define ID_ITEMLEVEL_01                 32782
#define ID_ITEMLEVEL_02                 32783
#define ID_ITEMLEVEL_03                 32784
#define ID_ITEMLEVEL_04                 32785
#define ID_ITEMLEVEL_05                 32786
#define ID_ITEMLEVEL_06                 32787
#define ID_ITEMLEVEL_07                 32788
#define ID_ITEMLEVEL_08                 32789
#define ID_ITEMLEVEL_09                 32790
#define ID_ITEMLEVEL_10                 32791
#define ID_ITEMLEVEL_11                 32792
#define ID_EDIT_SMATRIX_MOVE            32793
#define ID_EDIT_SMATRIX_ROTATE          32794
#define ID_EDIT_SMATRIX_SCALE           32795
#define ID_EDIT_BOX_MOVE                32796
#define ID_EDIT_BOX_SCALE               32797
#define ID_EDIT_BOX_SELSCALE            32798
#define ID_EDIT_MATRIX_MOVE             32799
#define ID_EDIT_MATRIX_ROTATE           32800
#define ID_EDIT_MATRIX_SCALE            32801
#define ID_DETECT_SELECT_CROW           32802
#define ID_DETECT_SELECT_GATE           32803
#define ID_EDITMATRIX_MATRIXMOVE        32804
#define ID_EDITMATRIX_MATRIXROTATE      32805
#define ID_EDITMATRIX_MATRIXSCALE       32806

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        316
#define _APS_NEXT_COMMAND_VALUE         32807
#define _APS_NEXT_CONTROL_VALUE         1048
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
