//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EditorNpcAction.rc
//
#define ID_NTK_LOAD                     3
#define ID_NTK_SAVE                     4
#define ID_NTK_NEW                      5
#define IDD_EDITORNPCACTION_DIALOG      102
#define IDD_PAGE_TABLE                  108
#define IDD_PAGE_ACTION                 109
#define IDD_PAGE_ANSWER                 110
#define IDD_PAGE_CONDITION              111
#define IDD_PAGE_TALK                   113
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_NUM                  130
#define IDD_DIALOG_ITEM                 132
#define IDD_DIALOG_SKILL                133
#define IDD_DIALOG_QUEST                134
#define IDD_DIALOG_SKILL2               135
#define IDD_DIALOG_TALK                 136
#define IDC_STATIC_TOOL                 1000
#define IDC_BUTTON_ADD                  1000
#define IDC_BUTTON_EDIT                 1001
#define IDC_EDIT_STATEMENT              1001
#define IDC_EDIT_CONDITION              1002
#define IDC_BUTTON_COPY                 1003
#define IDC_BUTTON_DATA_NEW             1003
#define IDC_BUTTON5                     1004
#define IDC_BUTTON_DELETE               1004
#define IDC_BUTTON_DATA_EDIT            1004
#define IDC_BUTTON_DATA_COPY            1005
#define IDC_BUTTON_SEARCH               1005
#define IDC_BUTTON_DATA_DELETE          1006
#define IDC_BUTTON_DATA_UP              1007
#define IDC_BUTTON_DATA_DOWN            1008
#define IDC_BUTTON_OK                   1009
#define IDC_BUTTON_CANCEL               1010
#define IDC_LIST_STATEMENT              1011
#define IDC_EDIT_STATEMENT_ID           1012
#define IDC_BUTTON_CONDITION_EDIT       1013
#define IDC_EDIT_SEARCH                 1013
#define IDC_BUTTON_CONDITION_DELETE     1014
#define IDC_BUTTON_ANSWER_ADD           1015
#define IDC_LIST_TALK                   1016
#define IDC_BUTTON_ANSWER_EDIT          1016
#define IDC_LISTCONT_ITEM               1016
#define IDC_LIST_ANSWER                 1017
#define IDC_BUTTON_ANSWER_COPY          1017
#define IDC_BUTTON_ANSWER_DELETE        1018
#define IDC_BUTTON_ANSWER_DELETEALL     1019
#define IDC_LIST_COMQUEST               1019
#define IDC_BUTTON_ANSWER_UP            1020
#define IDC_LIST_DIS_QUEST              1020
#define IDC_BUTTON_ANSWER_DOWN          1021
#define IDC_LIST_QUEST_STEP             1021
#define IDC_EDIT_SEL_MID                1021
#define IDC_LIST_ANSWERS                1022
#define IDC_LIST_SKILL                  1022
#define IDC_EDIT_SEL_SID                1022
#define IDC_BUTTON_ITEM_DELALL          1023
#define IDC_EDIT_SEL_NAME               1023
#define IDC_BUTTON_ITEM_DEL             1024
#define IDC_EDIT_SEL_LEVEL              1024
#define IDC_BUTTON_ITEM_ADD             1025
#define IDC_LIST_SELECT                 1025
#define IDC_BUTTON_ITEM_INSERT          1026
#define IDC_COMBO_SCHOOL                1027
#define IDC_COMBO_LEVEL_SIGN            1028
#define IDC_EDIT_LEVEL                  1029
#define IDC_CHECK_TIME                  1030
#define IDC_LIST_DIS_SKILL              1031
#define IDC_EDIT_COMQUEST_ID            1032
#define IDC_EDIT_SEL_ID                 1032
#define IDC_EDIT_DIS_QUEST_ID           1033
#define IDC_COMBO_LEVEL                 1033
#define IDC_EDIT_QUEST_INSERT_ID        1034
#define IDC_EDIT_TALKID                 1034
#define IDC_BUTTON_COMQUEST_DELALL      1035
#define IDC_EDIT_TALK                   1035
#define IDC_COMBO_ELEMENTAL_SIGN        1036
#define IDC_COMBO_ACTION_TYPE           1036
#define IDC_EDIT_ELEMENTAL              1037
#define IDC_EDIT_QUEST_0                1037
#define IDC_COMBO_BRIGHTPOINT_SIGN      1038
#define IDC_COMBO_ACTION_DATA           1038
#define IDC_EDIT_BRIGHTPOINT            1039
#define IDC_BUTTON_QUEST_ADD_0          1039
#define IDC_COMBO_TIME_BEGIN            1040
#define IDC_BUTTON_QUEST_DEL_0          1040
#define IDC_COMBO_TIME_END              1041
#define IDC_BUTTON_QUEST_INSERT_0       1041
#define IDC_EDIT_MONEY                  1042
#define IDC_EDIT_QUEST_INSERT_0         1042
#define IDC_EDIT_PARTY                  1043
#define IDC_EDIT_QUEST_1                1043
#define IDC_BUTTON_COMQUEST_DEL         1044
#define IDC_BUTTON_QUEST_ADD_1          1044
#define IDC_BUTTON_COMQUEST_ADD         1045
#define IDC_BUTTON_QUEST_DEL_1          1045
#define IDC_BUTTON_COMQUEST_INSERT      1046
#define IDC_BUTTON_QUEST_INSERT_1       1046
#define IDC_BUTTON_DIS_QUEST_DELALL     1047
#define IDC_EDIT_QUEST_INSERT_1         1047
#define IDC_BUTTON_DIS_QUEST_DEL        1048
#define IDC_EDIT_QUEST_2                1048
#define IDC_BUTTON_DIS_QUEST_ADD        1049
#define IDC_BUTTON_QUEST_ADD_2          1049
#define IDC_BUTTON_DIS_QUEST_INSERT     1050
#define IDC_BUTTON_QUEST_DEL_2          1050
#define IDC_BUTTON_SKILL_DELALL         1051
#define IDC_BUTTON_QUEST_INSERT_2       1051
#define IDC_BUTTON_QUEST_DEL            1052
#define IDC_EDIT_QUEST_INSERT_2         1052
#define IDC_BUTTON_QUEST_ADD            1053
#define IDC_EDIT_QUEST_3                1053
#define IDC_BUTTON_QUEST_INSERT         1054
#define IDC_BUTTON_QUEST_ADD_3          1054
#define IDC_BUTTON_SKILL_DEL            1055
#define IDC_BUTTON_QUEST_DEL_3          1055
#define IDC_BUTTON_SKILL_ADD            1056
#define IDC_BUTTON_QUEST_INSERT_3       1056
#define IDC_BUTTON_SKILL_INSERT         1057
#define IDC_EDIT_QUEST_INSERT_3         1057
#define IDC_EDIT_SKILL_MID              1058
#define IDC_EDIT_QUEST_4                1058
#define IDC_BUTTON_ALL_MALE             1059
#define IDC_BUTTON_QUEST_ADD_4          1059
#define IDC_EDIT_SKILL_SID              1060
#define IDC_BUTTON_QUEST_DEL_4          1060
#define IDC_BUTTON_DIS_SKILL_DELLALL    1061
#define IDC_BUTTON_QUEST_INSERT_4       1061
#define IDC_BUTTON_DIS_SKILL_DEL        1062
#define IDC_EDIT_QUEST_INSERT_4         1062
#define IDC_CHECK_REQ_CLASS_BRAWLER_M   1063
#define IDC_EDIT_BUS_LIST               1063
#define IDC_CHECK_REQ_CLASS_SWORDSMAN_M 1064
#define IDC_BUTTON_BUSLIST              1064
#define IDC_CHECK_REQ_CLASS_ARCHER_M    1065
#define IDC_EDIT_QUEST_PROG             1065
#define IDC_CHECK_REQ_CLASS_SHAMAN_M    1066
#define IDC_BUTTON_QUEST_ADD_PROG       1066
#define IDC_CHECK_REQ_CLASS_EXTREME_M   1067
#define IDC_BUTTON_QUEST_DEL_PROG       1067
#define IDC_BUTTON_DIS_SKILL_ADD        1068
#define IDC_BUTTON_QUEST_INSERT_PROG    1068
#define IDC_BUTTON_DIS_SKILL_INSERT     1069
#define IDC_EDIT_QUEST_INSERT_PROG      1069
#define IDC_EDIT_DIS_SKILL_MID          1070
#define IDC_EDIT_DIS_SKILL_SID          1071
#define IDC_EDIT_ITEM                   1071
#define IDC_BUTTON_ALL_FEMALE           1072
#define IDC_BUTTON_ALL                  1073
#define IDC_BUTTON_NOTHING              1074
#define IDC_CHECK_REQ_CLASS_SWORDSMAN_F 1075
#define IDC_EDIT_ITEM_INSERT_MID        1075
#define IDC_CHECK_REQ_CLASS_BRAWLER_F   1076
#define IDC_EDIT_ITEM_REQ_0             1076
#define IDC_CHECK_REQ_CLASS_ARCHER_F    1077
#define IDC_EDIT_ITEM_REQ_1             1077
#define IDC_CHECK_REQ_CLASS_SHAMAN_F    1078
#define IDC_EDIT_ITEM_REQ_2             1078
#define IDC_CHECK_REQ_CLASS_EXTREME_F   1079
#define IDC_EDIT_ITEM_REQ_3             1079
#define IDC_EDIT_ITEM_MID               1080
#define IDC_EDIT_ITEM_REQ_4             1080
#define IDC_EDIT_ITEM_SID               1081
#define IDC_EDIT_ITEM_INSERT_SID        1081
#define IDC_EDIT_QUEST_ID               1082
#define IDC_EDIT_ITEM_RES_00            1082
#define IDC_EDIT_QUEST                  1083
#define IDC_EDIT_ITEM_RES_01            1083
#define IDC_EDIT_QUEST_STEP             1084
#define IDC_BUTTON_QUEST_STEP           1085
#define IDC_CHECK_REQ_CLASS_GUNNER_M    1086
#define IDC_EDIT_ITEM_RES_02            1086
#define IDC_EDIT_SKILL_LEVEL            1087
#define IDC_EDIT_ITEM_RES_03            1087
#define IDC_CHECK_REQ_CLASS_EXTREME_F2  1088
#define IDC_CHECK_REQ_CLASS_GUNNER_F    1088
#define IDC_EDIT_ITEM_RES_04            1088
#define IDC_CHECK_REQ_ENABLE            1089
#define IDC_EDIT_ITEM_NUM               1090
#define IDC_CHECK_REQ_CLASS_ASSASSIN_M  1091
#define IDC_CHECK_REQ_CLASS_ASSASSIN_F  1092
#define IDC_CHECK_REQ_CLASS_TRICKER_M   1093
#define IDC_CHECK_REQ_CLASS_GUNNER_F3   1094
#define IDC_CHECK_REQ_CLASS_TRICKER_F   1094
#define IDC_BUTTON_RANDOM_RESET         1095
#define IDC_BUTTON_SKILL_DELALL2        1095
#define IDC_BUTTON_BUFF_DELALL          1095
#define IDC_EDIT_RANDOM_TIME            1096
#define IDC_BUTTON_BUFF_DEL             1096
#define IDC_BUTTON_RANDOM_ADD           1097
#define IDC_BUTTON_BUFF_ADD             1097
#define IDC_LIST_CASE_RANDOM            1098
#define IDC_BUTTON_BUFF_INSERT          1098
#define IDC_BUTTON_RANDOM_DEL           1099
#define IDC_LIST_BUFF                   1099
#define IDC_STATIC_QUEST_START          1100
#define IDC_EDIT_BUFF_MID               1100
#define IDC_STATIC_TRADE                1101
#define IDC_EDIT_BUFF_SID               1101
#define IDC_STATIC_QUEST_STEP_TEXT_0    1102
#define IDC_EDIT_BUFF_LEVEL             1102
#define IDC_STATIC_PROG_QUEST           1103
#define IDC_STATIC_REQ_ITEM_0           1104
#define IDC_STATIC_REQ_ITEM_1           1105
#define IDC_STATIC_REQ_ITEM_2           1106
#define IDC_STATIC_REQ_ITEM_3           1107
#define IDC_STATIC_REQ_ITEM_4           1108
#define IDC_STATIC_RANDOM_TIME_TEXT     1109
#define IDC_STATIC_RANDOMTIME           1110
#define IDC_STATIC_RANDOM_TIME_GROUP    1110
#define IDC_STATIC_RES_ITEM_00          1111
#define IDC_STATIC_RES_ITEM_01          1112
#define IDC_STATIC_RES_ITEM_02          1113
#define IDC_STATIC_RES_ITEM_03          1114
#define IDC_BUTTON_NTK_SAVEALL          1115
#define IDC_STATIC_REQ_ITEM_9           1115
#define IDC_STATIC_RES_ITEM_04          1115
#define IDC_BUTTON_NTK_CLASSCNV         1116
#define IDC_EDIT_NUM                    1117
#define IDC_BUTTON_NTK_CLASSCNV2        1117
#define IDC_BUTTON_NTK_DECOMPILE_DAT    1117
#define IDC_COMBO_SEARCH                1125

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32796
#define _APS_NEXT_CONTROL_VALUE         1118
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
