//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EditorActivity.rc
//
#define IDD_EDITORACTIVITY_DIALOG       102
#define IDR_MAINFRAME                   128
#define IDD_DLG_FIND_QUEST              159
#define IDD_DLG_FIND_ITEM               169
#define IDD_DLG_FIND_CROW               187
#define IDD_DLG_FIND_MAP                323
#define IDC_BUTTON_FILE_LOAD            1000
#define IDC_BUTTON_FILE_SAVE            1001
#define IDC_EDIT_ID                     1002
#define IDC_BUTTON_ADD                  1003
#define IDC_BUTTON_EDIT                 1004
#define IDC_BUTTON_DELETE               1005
#define IDC_BUTTON_CLEAR                1006
#define IDC_COMBO_TYPE                  1008
#define IDC_COMBO_NOTIFY                1009
#define IDC_EDIT_TITLE                  1010
#define IDC_CHECK_BADGE                 1011
#define IDC_EDIT_BADGE                  1012
#define IDC_EDIT_REWARD_POINT           1013
#define IDC_BUTTON_SAVE                 1014
#define IDC_EDIT_PROGRESS_LEVEL         1015
#define IDC_LIST_ACTIVITY               1016
#define IDC_LIST                        1016
#define IDC_BUTTON_MOB_KILL             1017
#define IDC_EDIT_PROGRESS_MOB_KILL_NAME 1018
#define IDC_EDIT_PROGRESS_MOB_KILL_NUM  1019
#define IDC_EDIT_PROGRESS_MOB_KILL_MID  1020
#define IDC_EDIT_PROGRESS_MOB_KILL_SID  1021
#define IDC_BUTTON_MAP_KILL             1022
#define IDC_EDIT_PROGRESS_MAP_KILL_NAME 1023
#define IDC_EDIT_PROGRESS_MAP_KILL_NUM  1024
#define IDC_EDIT_PROGRESS_MAP_KILL_MID  1025
#define IDC_EDIT_PROGRESS_MAP_KILL_SID  1026
#define IDC_EDIT_DESC                   1027
#define IDC_BUTTON_MAP_REACH            1028
#define IDC_EDIT_PROGRESS_MAP_REACH_NAME 1029
#define IDC_EDIT_PROGRESS_MAP_REACH_NUM 1030
#define IDC_EDIT_PROGRESS_MAP_REACH_MID 1031
#define IDC_EDIT_PROGRESS_MAP_REACH_SID 1032
#define IDC_BUTTON_TAKE_ITEM            1033
#define IDC_EDIT_PROGRESS_TAKE_ITEM_NAME 1034
#define IDC_EDIT_PROGRESS_TAKE_ITEM_NUM 1035
#define IDC_EDIT_PROGRESS_TAKE_ITEM_MID 1036
#define IDC_EDIT_PROGRESS_TAKE_ITEM_SID 1037
#define IDC_BUTTON_USE_ITEM             1038
#define IDC_EDIT_PROGRESS_USE_ITEM_NAME 1039
#define IDC_EDIT_PROGRESS_USE_ITEM_NUM  1040
#define IDC_EDIT_PROGRESS_USE_ITEM_MID  1041
#define IDC_EDIT_PROGRESS_USE_ITEM_SID  1042
#define IDC_COMBO_USE_QBOX              1043
#define IDC_EDIT_PROGRESS_USE_QBOX      1044
#define IDC_BUTTON_COMPLETE_QUEST       1045
#define IDC_EDIT_PROGRESS_COMPLETE_QUEST_NAME 1046
#define IDC_BUTTON_OK                   1047
#define IDC_EDIT_PROGRESS_COMPLETE_QUEST_NUM 1047
#define IDC_EDIT_PROGRESS_COMPLETE_QUEST_ID 1048
#define IDC_EDIT_PROGRESS_ACTIVITY_POINT 1050
#define IDC_EDIT_PROGRESS_ACTIVITY_POINT2 1051
#define IDC_EDIT_TOTAL_ACTIVITY         1051
#define IDC_COMBO_QUEST_SEARCH          1068
#define IDC_EDIT_QUEST_SEARCH           1069
#define IDC_COMBO_ITEM_SEARCH           1071
#define IDC_EDIT_ITEM_SEARCH            1072
#define IDC_STATIC_FILTER_INFO          1083
#define IDC_COMBO_MAP_SEARCH            1103
#define IDC_EDIT_MAP_SEARCH             1104
#define IDC_BUTTON_HELPER_SEARCH        1136
#define IDC_COMBO_CROW_SEARCH           1140
#define IDC_EDIT_CROW_SEARCH            1141

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1018
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
