/*!
 * \file GLActivityDefine.h
 *
 * \author Juver
 * \date October 2017
 *
 * 
 */

#ifndef GLACTIVITY_DEFINE_H_
#define GLACTIVITY_DEFINE_H_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#define ACTIVITY_TITLE_MSG_SIZE 250
#define CHARACTER_BADGE_TIME 2.0f


enum EMACTIVITY_NOTIFY
{
	EMACTIVITY_NOTIFY_NONE			= 0,
	EMACTIVITY_NOTIFY_AROUND		= 1,
	EMACTIVITY_NOTIFY_ALLSERVER		= 2,
	EMACTIVITY_NOTIFY_SIZE			= 3,
};

enum EMACTIVITY_TYPE
{
	EMACTIVITY_TYPE_REACH_LEVEL		= 0,
	EMACTIVITY_TYPE_KILL_MOB		= 1,
	EMACTIVITY_TYPE_KILL_PLAYER		= 2,
	EMACTIVITY_TYPE_REACH_MAP		= 3,
	EMACTIVITY_TYPE_TAKE_ITEM		= 4,
	EMACTIVITY_TYPE_USE_ITEM		= 5,
	EMACTIVITY_TYPE_REACH_ACTIVITY	= 6,
	EMACTIVITY_TYPE_COMPLETE_QUEST	= 7,
	EMACTIVITY_TYPE_ACTIVITY_POINT	= 8,
	EMACTIVITY_TYPE_QUESTION_BOX	= 9,
	EMACTIVITY_TYPE_SIZE			= 10,
};

namespace COMMENT
{
	extern std::string ACTIVITY_NOTIFY[EMACTIVITY_NOTIFY_SIZE];
	extern std::string ACTIVITY_MID[EMACTIVITY_TYPE_SIZE];
};

#endif // GLACTIVITY_DEFINE_H_
