#pragma once


enum CAPTURE_THE_FLAG_REGISTER_FB
{
	CAPTURE_THE_FLAG_REGISTER_FB_FAILED				= 0,
	CAPTURE_THE_FLAG_REGISTER_FB_NOTPOSSIBLE		= 1,
	CAPTURE_THE_FLAG_REGISTER_FB_INVALID_CHANNEL	= 2,
	CAPTURE_THE_FLAG_REGISTER_FB_INVALID_CHARID		= 3,
	CAPTURE_THE_FLAG_REGISTER_FB_INVALID_SCHOOL		= 4,
	CAPTURE_THE_FLAG_REGISTER_FB_INVALID_TEAM		= 5,
	CAPTURE_THE_FLAG_REGISTER_FB_LEVEL_LOW			= 6,
	CAPTURE_THE_FLAG_REGISTER_FB_ALREADY_REG		= 7,
	CAPTURE_THE_FLAG_REGISTER_FB_OTHER_TEAM			= 8,
	CAPTURE_THE_FLAG_REGISTER_FB_TEAM_A_FULL		= 9,
	CAPTURE_THE_FLAG_REGISTER_FB_TEAM_B_FULL		= 10,
	CAPTURE_THE_FLAG_REGISTER_FB_REGISTERED_A		= 11,
	CAPTURE_THE_FLAG_REGISTER_FB_REGISTERED_B		= 12,
	CAPTURE_THE_FLAG_REGISTER_FB_TEAM_A_BALANCE		= 13,
	CAPTURE_THE_FLAG_REGISTER_FB_TEAM_B_BALANCE		= 14,
	CAPTURE_THE_FLAG_REGISTER_FB_CANCEL_REG			= 15,
	CAPTURE_THE_FLAG_REGISTER_FB_CANCEL_FAIL		= 16,
	CAPTURE_THE_FLAG_REGISTER_FB_CONTRI_LOW			= 17,
};

enum CAPTURE_THE_FLAG_REJOIN_FB
{
	CAPTURE_THE_FLAG_REJOIN_FB_FAILED				= 0,
	CAPTURE_THE_FLAG_REJOIN_FB_NOTPOSSIBLE			= 1,
	CAPTURE_THE_FLAG_REJOIN_FB_NOT_REGISTERED		= 2,
	CAPTURE_THE_FLAG_REJOIN_FB_INVALID_CHARID		= 3,
	CAPTURE_THE_FLAG_REJOIN_FB_INBATTLE				= 4,
	CAPTURE_THE_FLAG_REJOIN_FB_INVALID_TEAM			= 5,
};

