#pragma once


/*event map move, Juver, 2017/08/25 */
enum EMEVENT_MOVEMAP_FB
{
	EMEVENT_MOVEMAP_FB_FAIL			= 0,
	EMEVENT_MOVEMAP_FB_CONDITION	= 1,
	EMEVENT_MOVEMAP_FB_OK			= 2,
};

/*charinfoview , Juver, 2017/11/11 */
enum EMREQ_CHARINFO_FB
{
	EMREQ_CHARINFO_FB_INVALID_TARGET	= 0,
	EMREQ_CHARINFO_FB_TIMEDELAY			= 1,
	EMREQ_CHARINFO_FB_WEARINFO			= 2,
	EMREQ_CHARINFO_FB_OK				= 3,
};

/*bike color , Juver, 2017/11/13 */
enum EMREQ_CHANGE_BIKE_COLOR_FB
{
	EMREQ_CHANGE_BIKE_COLOR_FB_CHANGE_FAIL		= 0,
	EMREQ_CHANGE_BIKE_COLOR_FB_INVALID_CARD		= 1,
	EMREQ_CHANGE_BIKE_COLOR_FB_VEHICLE_INACTIVE	= 2,
	EMREQ_CHANGE_BIKE_COLOR_FB_VEHICLE_NOT_BIKE	= 3,
	EMREQ_CHANGE_BIKE_COLOR_FB_CHANGE_DONE		= 4,
};

/*change scale card, Juver, 2018/01/04 */
enum EMFB_CHANGE_SCALE
{
	EMFB_CHANGE_SCALE_FAIL		= 0,
	EMFB_CHANGE_SCALE_OK		= 1,
	EMFB_CHANGE_SCALE_NOT_CARD	= 2,
};

/*item color, Juver, 2018/01/10 */
enum EMFB_ITEM_COLOR_CHANGE
{
	EMFB_ITEM_COLOR_CHANGE_FAILED		= 0,
	EMFB_ITEM_COLOR_CHANGE_NOT_CARD		= 1,
	EMFB_ITEM_COLOR_CHANGE_SLOT_ERROR	= 2,
	EMFB_ITEM_COLOR_CHANGE_DONE			= 3,
};

/*item wrapper, Juver, 2018/01/11 */
enum EMFB_ITEM_WRAP
{
	EMFB_ITEM_WRAP_FAILED				= 0,
	EMFB_ITEM_WRAP_TARGET_NOT_VALID		= 1,
	EMFB_ITEM_WRAP_TARGET_HAVE_DISGUISE	= 2,
	EMFB_ITEM_WRAP_HOLD_INVALID			= 3,
	EMFB_ITEM_WRAP_HOLD_NOT_WRAPPER		= 4,
	EMFB_ITEM_WRAP_HOLD_NOT_BOX			= 5,
	EMFB_ITEM_WRAP_TARGET_NO_NEED		= 6,
	EMFB_ITEM_WRAP_DONE					= 7,
};

/*item wrapper, Juver, 2018/01/12 */
enum EMFB_ITEM_UNWRAP
{
	EMFB_ITEM_UNWRAP_FAILED				= 0,
	EMFB_ITEM_UNWRAP_TARGET_NOT_VALID	= 1,
	EMFB_ITEM_UNWRAP_DONE				= 2,
};

/*change school card, Juver, 2018/01/12 */
enum EMFB_CHANGE_SCHOOL
{
	EMFB_CHANGE_SCHOOL_FAILED			= 0,
	EMFB_CHANGE_SCHOOL_NOT_CARD			= 1,
	EMFB_CHANGE_SCHOOL_NOT_SELECTED		= 2,
	EMFB_CHANGE_SCHOOL_REQ_CLEAN_QUEST	= 3,
	EMFB_CHANGE_SCHOOL_REQ_CLEAN_GUILD	= 4,
	EMFB_CHANGE_SCHOOL_REQ_MAX_LEVEL	= 5,
	EMFB_CHANGE_SCHOOL_SAME_SCHOOL		= 6,
	EMFB_CHANGE_SCHOOL_DONE				= 7,
};

/*equipment lock, Juver, 2018/01/14 */
enum EMFB_EQUIPMENT_LOCK_ENABLE
{
	EMFB_EQUIPMENT_LOCK_ENABLE_FAILED			= 0,
	EMFB_EQUIPMENT_LOCK_ENABLE_NOT_CARD			= 1,
	EMFB_EQUIPMENT_LOCK_ENABLE_ALREADY_ENABLED	= 2,
	EMFB_EQUIPMENT_LOCK_ENABLE_KEY_EMPTY		= 3,
	EMFB_EQUIPMENT_LOCK_ENABLE_KEY_SIZE			= 4,
	EMFB_EQUIPMENT_LOCK_ENABLE_KEY_NOT_SAME		= 5,
	EMFB_EQUIPMENT_LOCK_ENABLE_KEY_NUMBER_ONLY	= 6,
	EMFB_EQUIPMENT_LOCK_ENABLE_ALREADY_ENABLED_DB	= 7,
	EMFB_EQUIPMENT_LOCK_ENABLE_CHAR_NOT_EXIST		= 8,
	EMFB_EQUIPMENT_LOCK_ENABLE_DONE					= 9,
};

/*equipment lock, Juver, 2018/01/16 */
enum EMFB_EQUIPMENT_LOCK_INPUT
{
	EMFB_EQUIPMENT_LOCK_INPUT_FAILED			= 0,
	EMFB_EQUIPMENT_LOCK_INPUT_NOT_ENABLED		= 1,
	EMFB_EQUIPMENT_LOCK_INPUT_KEY_EMPTY			= 2,
	EMFB_EQUIPMENT_LOCK_INPUT_KEY_SIZE			= 3,
	EMFB_EQUIPMENT_LOCK_INPUT_KEY_NUMBER_ONLY	= 4,
	EMFB_EQUIPMENT_LOCK_INPUT_DATA_NOT_EXIST	= 5,
	EMFB_EQUIPMENT_LOCK_INPUT_TIMER				= 6,
	EMFB_EQUIPMENT_LOCK_INPUT_DONE				= 7,
};

/*equipment lock, Juver, 2018/01/16 */
enum EMFB_EQUIPMENT_LOCK_RECOVER
{
	EMFB_EQUIPMENT_LOCK_RECOVER_FAILED			= 0,
	EMFB_EQUIPMENT_LOCK_RECOVER_NOT_ENABLED		= 1,
	EMFB_EQUIPMENT_LOCK_RECOVER_NOT_CARD		= 2,
	EMFB_EQUIPMENT_LOCK_RECOVER_NOT_EXIST		= 3,
	EMFB_EQUIPMENT_LOCK_RECOVER_DONE			= 4,
};

/*equipment lock, Juver, 2018/01/17 */
enum EMFB_EQUIPMENT_LOCK_RECOVER_CHANGE
{
	EMFB_EQUIPMENT_LOCK_RECOVER_CHANGE_FAILED			= 0,
	EMFB_EQUIPMENT_LOCK_RECOVER_CHANGE_KEY_EMPTY		= 1,
	EMFB_EQUIPMENT_LOCK_RECOVER_CHANGE_KEY_SIZE			= 2,
	EMFB_EQUIPMENT_LOCK_RECOVER_CHANGE_KEY_NOT_SAME		= 3,
	EMFB_EQUIPMENT_LOCK_RECOVER_CHANGE_KEY_NUMBER_ONLY	= 4,
	EMFB_EQUIPMENT_LOCK_RECOVER_CHANGE_NOT_ENABLED		= 5,
	EMFB_EQUIPMENT_LOCK_RECOVER_CHANGE_NOT_FOUND		= 6,
	EMFB_EQUIPMENT_LOCK_RECOVER_CHANGE_DONE				= 7,
};

/*equipment lock, Juver, 2018/01/18 */
enum EMFB_EQUIPMENT_LOCK_RECOVER_DELETE
{
	EMFB_EQUIPMENT_LOCK_RECOVER_DELETE_FAILED			= 0,
	EMFB_EQUIPMENT_LOCK_RECOVER_DELETE_NOT_FOUND		= 1,
	EMFB_EQUIPMENT_LOCK_RECOVER_DELETE_NOT_ENABLED		= 2,
	EMFB_EQUIPMENT_LOCK_RECOVER_DELETE_DONE				= 3,
};

/*item transfer card, Juver, 2018/01/18 */
enum EMFB_ITEM_TRANSFER
{
	EMFB_ITEM_TRANSFER_FAILED				= 0,
	EMFB_ITEM_TRANSFER_NOT_CARD				= 1,
	EMFB_ITEM_TRANSFER_INVALID_ITEM			= 2,
	EMFB_ITEM_TRANSFER_INVALID_ITEM_TYPE	= 3,
	EMFB_ITEM_TRANSFER_TIME_LIMIT			= 4,
	EMFB_ITEM_TRANSFER_DISGUISE				= 5,
	EMFB_ITEM_TRANSFER_SUIT_MISMATCH		= 6,
	EMFB_ITEM_TRANSFER_ATTACK_MISMATCH		= 7,
	EMFB_ITEM_TRANSFER_COST					= 8,
	EMFB_ITEM_TRANSFER_HAVE_DISGUISE		= 9,
	EMFB_ITEM_TRANSFER_NOT_TRANSFER_ITEM	= 10,
	EMFB_ITEM_TRANSFER_DONE					= 11,
};

/* car, cart color, Juver, 2018/02/14 */
enum EMREQ_CHANGE_CAR_COLOR_FB
{
	EMREQ_CHANGE_CAR_COLOR_FB_CHANGE_FAIL		= 0,
	EMREQ_CHANGE_CAR_COLOR_FB_INVALID_CARD		= 1,
	EMREQ_CHANGE_CAR_COLOR_FB_VEHICLE_INACTIVE	= 2,
	EMREQ_CHANGE_CAR_COLOR_FB_VEHICLE_NOT_CAR	= 3,
	EMREQ_CHANGE_CAR_COLOR_FB_CHANGE_DONE		= 4,
};

/* booster all vehicle, Juver, 2018/02/14 */
enum EMALLVEHICLE_REQ_ENABLE_BOOSTER_FB
{
	EMALLVEHICLE_REQ_ENABLE_BOOSTER_FB_OK				= 0,
	EMALLVEHICLE_REQ_ENABLE_BOOSTER_FB_FAIL				= 1,
	EMALLVEHICLE_REQ_ENABLE_BOOSTER_FB_INVALID_CARD		= 2,
	EMALLVEHICLE_REQ_ENABLE_BOOSTER_FB_INVALID_ITEM		= 3,
	EMALLVEHICLE_REQ_ENABLE_BOOSTER_FB_INVALID_TYPE		= 4,
	EMALLVEHICLE_REQ_ENABLE_BOOSTER_FB_ALREADY_ENABLED	= 5,
};