#pragma once


enum SCHOOLWARS_REGISTER_FB
{
	SCHOOLWARS_REGISTER_FB_FAILED			= 0,
	SCHOOLWARS_REGISTER_FB_NOTPOSSIBLE		= 1,
	SCHOOLWARS_REGISTER_FB_INVALID_CHANNEL	= 2,
	SCHOOLWARS_REGISTER_FB_INVALID_CHARID	= 3,
	SCHOOLWARS_REGISTER_FB_INVALID_SCHOOL	= 4,
	SCHOOLWARS_REGISTER_FB_LEVEL_LOW		= 5,
	SCHOOLWARS_REGISTER_FB_ALREADY_REG		= 6,
	SCHOOLWARS_REGISTER_FB_ALREADY_QUEUE	= 7,
	SCHOOLWARS_REGISTER_FB_QUEUED			= 8,
	SCHOOLWARS_REGISTER_FB_REGISTERED		= 9,
	SCHOOLWARS_REGISTER_FB_CANCEL_REG		= 10,
	SCHOOLWARS_REGISTER_FB_CANCEL_FAIL		= 11,
	SCHOOLWARS_REGISTER_FB_CONTRI_LOW		= 12,
};

enum SCHOOLWARS_REJOIN_FB
{
	SCHOOLWARS_REJOIN_FB_FAILED				= 0,
	SCHOOLWARS_REJOIN_FB_NOTPOSSIBLE		= 1,
	SCHOOLWARS_REJOIN_FB_NOT_REGISTERED		= 2,
	SCHOOLWARS_REJOIN_FB_INVALID_CHARID		= 3,
	SCHOOLWARS_REJOIN_FB_INBATTLE			= 4,
};