#pragma once

enum EMNPC_ITEM_EXCHANGE_FB
{
	EMNPC_ITEM_EXCHANGE_FB_OK					= 0,
	EMNPC_ITEM_EXCHANGE_FB_INVALID_NPC			= 1,
	EMNPC_ITEM_EXCHANGE_FB_INVALID_ID			= 2,
	EMNPC_ITEM_EXCHANGE_FB_INVALID_ITEM			= 3,
	EMNPC_ITEM_EXCHANGE_FB_NOCONTRIBUTIONPOINT	= 4,
	EMNPC_ITEM_EXCHANGE_FB_NOPOINT				= 5,
	EMNPC_ITEM_EXCHANGE_FB_NOT_INVEN_SPACE		= 6,
	EMNPC_ITEM_EXCHANGE_FB_REQUIRE_MISSING		= 7,
	EMNPC_ITEM_EXCHANGE_FB_DELETE_FAIL			= 8,
	EMNPC_ITEM_EXCHANGE_FB_INSERT_FAIL			= 9,
};

enum RAN_PRODUCT_FB
{
	RAN_PRODUCT_FB_STARTED						= 0,
	RAN_PRODUCT_FB_INVALID_ID					= 1,
	RAN_PRODUCT_FB_INVALID_COST					= 2,
	RAN_PRODUCT_FB_INVALID_CHAR_LEVEL			= 3,
	RAN_PRODUCT_FB_RESULT_ITEM_INVALID			= 4,
	RAN_PRODUCT_FB_RESULT_ITEM_NO_SPACE			= 5,
	RAN_PRODUCT_FB_MATERIAL						= 6,
	RAN_PRODUCT_FB_FAIL_COSTUME					= 7,
	RAN_PRODUCT_FB_FAIL_DELETE					= 8,
	RAN_PRODUCT_FB_FAIL_INSERT					= 9,
	RAN_PRODUCT_FB_TASK_RUNNING					= 10,
	RAN_PRODUCT_FB_FEATURE_OFF					= 11,
};

enum RAN_PRODUCT_PROCESS_FB
{
	RAN_PRODUCT_PROCESS_FB_OK					= 0,
	RAN_PRODUCT_PROCESS_FB_FAILED				= 1,
	RAN_PRODUCT_PROCESS_FB_FULL_INVEN			= 2,
	RAN_PRODUCT_PROCESS_FB_FAILED_INSERT		= 3,
};

/*rv card, Juver, 2017/11/25 */
enum EM_RANDOM_OPTION_CHANGE_FB
{
	EM_RANDOM_OPTION_CHANGE_INVALID_CARD_ITEM			= 0,
	EM_RANDOM_OPTION_CHANGE_INVALID_TARGET_ITEM			= 1,
	EM_RANDOM_OPTION_CHANGE_TARGET_NOT_SUIT				= 2,
	EM_RANDOM_OPTION_CHANGE_SUIT_MISMATCH				= 3,
	EM_RANDOM_OPTION_CHANGE_TARGET_OPTION_NOT_EXIST		= 4,
	EM_RANDOM_OPTION_CHANGE_TARGET_OPTION_ALREADY_SET	= 5,
	EM_RANDOM_OPTION_CHANGE_TARGET_OPTION_NOT_FREE		= 6,
	EM_RANDOM_OPTION_CHANGE_DONE_CHANGE					= 7,
};

/*nondrop card, Juver, 2017/11/26 */
enum EM_NONDROP_CARD_FB
{
	EM_NONDROP_CARD_INVALID_CARD_ITEM			= 0,
	EM_NONDROP_CARD_INVALID_TARGET_ITEM			= 1,
	EM_NONDROP_CARD_TARGET_NOT_SUIT				= 2,
	EM_NONDROP_CARD_TARGET_ALREADY				= 3,
	EM_NONDROP_CARD_DONE_CHANGE					= 4,
};