/*!
 * \file GLPVPCaptureTheFlagDefine.h
 *
 * \author Juver
 * \date January 2018
 *
 * 
 */

#pragma once

#define CAPTURE_THE_FLAG_SCHEDULE_NONE				UINT_MAX
#define CAPTURE_THE_FLAG_CHARNAME_STRING_SIZE		33			//similar to CHAR_SZNAME
#define CAPTURE_THE_FLAG_PLAYER_NULL				0xFFFFFFFF	//similar to GAEAID_NULL
#define CAPTURE_THE_FLAG_MINI_RANKING_NUM			10			//top rankings size
#define CAPTURE_THE_FLAG_REVIVE_TIME				10.0f		//revive time
#define CAPTURE_THE_FLAG_PACKET_PLAYER_DATA_NUM		32			//agent to field player data
#define CAPTURE_THE_FLAG_PACKET_RANK_NUM			26			//field to client ranking data
#define CAPTURE_THE_FLAG_REG_NUM_BRD_TIME			10.0f		//time to broadcast member num
#define CAPTURE_THE_FLAG_DETECT_GATE_TIMER			2.0f		//time to detect gate
#define CAPTURE_THE_FLAG_HOLD_MAX_TIME				60.0f		//max time to hold flag
#define CAPTURE_THE_FLAG_FLAG_POS_BRD_TIME			2.0f		//to to check holder status

enum CAPTURE_THE_FLAG_STATE 
{
	CAPTURE_THE_FLAG_STATE_ENDED		= 0,
	CAPTURE_THE_FLAG_STATE_REGISTER		= 1,
	CAPTURE_THE_FLAG_STATE_BATTLE		= 2,
	CAPTURE_THE_FLAG_STATE_REWARD		= 3,
	CAPTURE_THE_FLAG_STATE_SIZE			= 4,
};

enum 
{
	CAPTURE_THE_FLAG_TEAM_A				= 0,
	CAPTURE_THE_FLAG_TEAM_B				= 1,
	CAPTURE_THE_FLAG_TEAM_SIZE			= 2,
	CAPTURE_THE_FLAG_INFO_SCHOOL_SIZE	= 3,
};

enum CAPTURE_THE_FLAG_FLAG_HOLD_STATUS
{
	CAPTURE_THE_FLAG_FLAG_HOLD_STATUS_NONE			= 0,
	CAPTURE_THE_FLAG_FLAG_HOLD_STATUS_TIMEOUT		= 1,
	CAPTURE_THE_FLAG_FLAG_HOLD_STATUS_LEFTBATTLE	= 2,
	CAPTURE_THE_FLAG_FLAG_HOLD_STATUS_DEAD			= 3,
	CAPTURE_THE_FLAG_FLAG_HOLD_STATUS_CAPTURE		= 4,
	CAPTURE_THE_FLAG_FLAG_HOLD_STATUS_SCORE			= 5,
};