

#pragma once

#define TOOL_MAIN_ZBIAS_SIZE 12
#define TOOL_EFFSINGLE_ANI_SIZE 3
#define TOOL_EFFSINGLE_WEATHER_SIZE 3
#define TOOL_EFFSINGLE_DOT_SIZE 9
#define TOOL_EFFBLUR_TRACE_SIZE 6
#define TOOL_EFFBLUR_BLEND_SIZE 5
#define TOOL_EFFLEVEL_MODULATE_SIZE 3
#define TOOL_EFFMARK_BLEND_SIZE 3
#define TOOL_EFFL2BONE_COLORSET_SIZE 4

namespace GLOBAL_EFFTOOL
{
	extern std::string strEFFMAIN_ZBIAS[TOOL_MAIN_ZBIAS_SIZE];
	extern std::string strEFFSINGLE_ANI[TOOL_EFFSINGLE_ANI_SIZE];
	extern std::string strEFFSINGLE_WEATHER[TOOL_EFFSINGLE_WEATHER_SIZE];
	extern std::string strEFFSINGLE_DOT[TOOL_EFFSINGLE_DOT_SIZE];
	extern std::string strEFFBLUR_TRACE[TOOL_EFFBLUR_TRACE_SIZE];
	extern std::string strEFFBLUR_BLEND[TOOL_EFFBLUR_BLEND_SIZE];
	extern std::string strEFFLEVEL_MODULATE[TOOL_EFFLEVEL_MODULATE_SIZE];
	extern std::string strEFFMARK_BLEND[TOOL_EFFMARK_BLEND_SIZE];
	extern std::string strEFFL2BONE_COLORSET[TOOL_EFFL2BONE_COLORSET_SIZE];
	
};