//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EditorSkinPiece.rc
//
#define ID_ADDCOLOUR                    3
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDD_DLG_COLOR                   129
#define IDR_RanEditSkinPiecTYPE         130
#define IDD_DLG_MAIN                    310
#define IDC_DRAGITEM                    310
#define IDD_PAGE_MAIN                   311
#define IDD_PAGE_EFF_00_SINGLE          313
#define IDD_PAGE_EFF_01_BLUR            314
#define IDD_PAGE_EFF_02_CLONEBLUR       315
#define IDD_PAGE_EFF_04_SHOCK           316
#define IDD_PAGE_EFF_06_ARROW           317
#define IDD_PAGE_EFF_08_LEVEL           318
#define IDD_PAGE_EFF_10_ALPHA           319
#define IDD_PAGE_EFF_11_NEON            320
#define IDD_PAGE_EFF_12_MARK            321
#define IDD_PAGE_EFF_13_NOALPHA         322
#define IDD_PAGE_EFF_14_REFLECTION2     323
#define IDD_PAGE_EFF_15_AMBIENT         324
#define IDD_PAGE_EFF_17_MULTITEX        325
#define IDD_PAGE_EFF_18_GHOSTING        326
#define IDD_PAGE_EFF_19_SPECULAR2       327
#define IDD_PAGE_EFF_20_TOON            328
#define IDD_PAGE_EFF_21_TEXDIFF         329
#define IDD_PAGE_EFF_22_PARTICLE        330
#define IDD_PAGE_EFF_23_BONEPOS         331
#define IDD_PAGE_EFF_24_BONELIST        332
#define IDD_PAGE_EFF_25_USERCOLOR       333
#define IDD_PAGE_EFF_26_NORMALMAP       334
#define IDD_PAGE_EFF_27_LINE2BONE       335
#define IDD_PAGE_EFF_28_AROUNDEFF       336
#define IDC_STATIC_TOOL                 1000
#define IDC_EDIT_FILENAME               1000
#define IDC_BUTTON_SKIN                 1001
#define IDC_EDIT_SKIN                   1002
#define IDC_EDIT_SKELETON               1003
#define IDC_HUE                         1003
#define IDC_BUTTON_SKELETON             1004
#define IDC_SAT                         1004
#define IDC_BUTTON_CREATESKIN           1005
#define IDC_LUM                         1005
#define IDC_COMBO_PIECE                 1006
#define IDC_RED                         1006
#define IDC_COMBO_SLOT                  1007
#define IDC_GREEN                       1007
#define IDC_BUTTON_TRACE_ADD            1008
#define IDC_BLUE                        1008
#define IDC_BUTTON_TRACE_DEL            1009
#define IDC_EDIT_ZTEXTURE               1010
#define IDC_EDIT_MESH                   1011
#define IDC_COMBO_ZBIAS                 1012
#define IDC_REF                         1012
#define IDC_BUTTON_MESH                 1013
#define IDC_BUTTON_EFF_ADD              1014
#define IDC_BUTTON_EFF_EDIT             1015
#define IDC_BUTTON_EDIT_APPLY           1015
#define IDC_LIST_TRACE                  1016
#define IDC_BUTTON_EDIT_SAVE            1016
#define IDC_LIST_MATERIAL               1017
#define IDC_BUTTON_EDIT_CLOSE           1017
#define IDC_LIST_MESH                   1018
#define IDC_EDIT_EFFECT                 1018
#define IDC_LIST_EFFECT                 1019
#define IDC_BUTTON_EFFECT               1019
#define IDC_BUTTON_EFF_DEL              1020
#define IDC_EDIT_TRACE_1                1020
#define IDC_BUTTON_EFF_UP               1021
#define IDC_LIST_TRACE_1                1021
#define IDC_BUTTON_EFF_DOWN             1022
#define IDC_EDIT_TRACE_MOVE_1           1022
#define IDC_LIST_TRACE_DOWN             1022
#define IDC_COMBO_EFFECT                1023
#define IDC_LIST_TRACE_2                1023
#define IDC_EDIT_TRACE_DOWN             1023
#define IDC_BUTTON_EFF_OK               1024
#define IDC_EDIT_TRACE_2                1024
#define IDC_BUTTON_MATERIAL_TEXTURE     1025
#define IDC_EDIT_TRACE_MOVE_2           1025
#define IDC_CHECK_DOT_1                 1026
#define IDC_BUTTON_EFF_SORT             1026
#define IDC_CHECK_DOT_2                 1027
#define IDC_BUTTON_TRACE_DELALL         1027
#define IDC_CHECK_DOT_MATRIX            1028
#define IDC_CHECK_MOVE_AUTO             1029
#define IDC_CHECK_MOVE_REPEAT           1030
#define IDC_EDIT_MOVE_SPEED             1031
#define IDC_CHECK_REPEAT                1032
#define IDC_EDIT_REPEAT_DELAY           1033
#define IDC_CHECK_DOT_MATRIX2           1034
#define IDC_CHECK_MOVE_REPEAT2          1035
#define IDC_CHECK_MATRIX2_USE2          1035
#define IDC_EDIT_SCALE                  1036
#define IDC_COMBO_ANISET                1037
#define IDC_COMBO_WEATHERSET            1038
#define IDC_EDIT_COLOR_A_UP             1038
#define IDC_BUTTON_SAVE                 1039
#define IDC_EDIT_COLOR_R_UP             1039
#define IDC_BUTTON_MATERIAL_SAVE        1040
#define IDC_BUTTON_CLOSE                1040
#define IDC_BUTTON_COLOR_UP             1040
#define IDC_BUTTON_APPLY                1041
#define IDC_EDIT_COLOR_G_UP             1041
#define IDC_EDIT_COLOR_B_UP             1042
#define IDC_EDIT_COLOR_R_UP_CB          1042
#define IDC_BUTTON_TEXTURE              1043
#define IDC_EDIT_TEXTURE                1044
#define IDC_EDIT_COLOR_A_DOWN           1045
#define IDC_BUTTON_COLOR_UP_CB          1045
#define IDC_EDIT_COLOR_R_DOWN           1046
#define IDC_EDIT_COLOR_G_UP_CB          1046
#define IDC_BUTTON_COLOR_DOWN           1047
#define IDC_EDIT_COLOR_B_UP_CB          1047
#define IDC_EDIT_COLOR_G_DOWN           1048
#define IDC_EDIT_COLOR_A_DOWN_CB        1048
#define IDC_EDIT_COLOR_B_DOWN           1049
#define IDC_EDIT_COLOR_R_DOWN_CB        1049
#define IDC_LIST_TRACE_UP               1050
#define IDC_EDIT_TRACE_UP               1051
#define IDC_COMBO_BLEND                 1052
#define IDC_BUTTON_COLOR_DOWN_CB        1052
#define IDC_CHECK_USE_REFRACTION        1053
#define IDC_EDIT_COLOR_G_DOWN_CB        1053
#define IDC_CHECK_USE_ALLACTION         1054
#define IDC_EDIT_COLOR_B_DOWN_CB        1054
#define IDC_EDIT_GENTIME                1055
#define IDC_COMBO_BLEND_CB              1055
#define IDC_EDIT_COLOR_A_UP_CB          1056
#define IDC_LIST_TRACE_UP_CB            1057
#define IDC_LIST_TRACE_DOWN_CB          1058
#define IDC_EDIT_TRACE_UP_CB            1059
#define IDC_EDIT_TRACE_DOWN_CB          1060
#define IDC_EDIT_TEXTURE_CB             1061
#define IDC_BUTTON_TEXTURE_CB           1062
#define IDC_CHECK_USE_BEZIER_CB         1063
#define IDC_EDIT_SH_FULLTIME            1063
#define IDC_EDIT_FACES_CB               1064
#define IDC_EDIT_SH_COLOR_A             1064
#define IDC_EDIT_WIDTH_CB               1065
#define IDC_EDIT_SH_COLOR_R             1065
#define IDC_EDIT_SH_COLOR_G             1066
#define IDC_EDIT_SH_COLOR_B             1067
#define IDC_BUTTON_SH_COLOR             1068
#define IDC_BUTTON_CA_EFFBASE           1069
#define IDC_BUTTON_CA_EFFUP             1070
#define IDC_EDIT_CA_EFFBASE             1071
#define IDC_EDIT_CA_EFFUP               1072
#define IDC_CHECK_CA_USEEFFECT          1073
#define IDC_CHECK_CA_USEROTATION        1074
#define IDC_CHECK_CA_USESEC             1075
#define IDC_EDIT_CA_SEC                 1076
#define IDC_CHECK_CA_USEARROW           1077
#define IDC_EDIT_CA_SIZE                1078
#define IDC_CHECK_CA_USESIZE            1079
#define IDC_EDIT_CA_FULLTIME            1080
#define IDC_EDIT_CA_ALPHATIME           1081
#define IDC_EDIT_CA_SETRATE             1082
#define IDC_EDIT_CA_DEPTH               1083
#define IDC_EDIT_CA_COLOR_A             1084
#define IDC_EDIT_CA_COLOR_R             1085
#define IDC_EDIT_CA_COLOR_G             1086
#define IDC_EDIT_CA_COLOR_B             1087
#define IDC_EDIT_CA_MESH                1088
#define IDC_COMBO_CA_BLEND              1089
#define IDC_BUTTON_CA_COLOR             1090
#define IDC_BUTTON_CA_MESH              1091
#define IDC_EDIT_CA_EFFRANGE            1092
#define IDC_CHECK_MATERIAL_USE          1093
#define IDC_EDIT_MATERIAL_TEXTURE       1095
#define IDC_BUTTON_MATERIAL_OK          1096
#define IDC_EDIT_MATERIAL_POWER         1097
#define IDC_COMBO_CL_COLOROP            1098
#define IDC_EDIT_CL_COLOR_A             1099
#define IDC_EDIT_CL_COLOR_R             1100
#define IDC_EDIT_CL_COLOR_G             1101
#define IDC_EDIT_CL_COLOR_B             1102
#define IDC_BUTTON_CL_COLOR             1103
#define IDC_EDIT_CL_POWER               1104
#define IDC_EDIT_CA_ALPHA               1104
#define IDC_EDIT_CA_PLAYTIME            1105
#define IDC_BUTTON_CRF_TEXTURE          1105
#define IDC_EDIT_CA_WAITTIME            1106
#define IDC_CHECK_CA_USE_TRANSLUCENT    1107
#define IDC_CHECK_CN_USE_GENERAL        1108
#define IDC_CHECK_CN_USE_BURN           1109
#define IDC_CHECK_CN_USE_ALLTEX         1110
#define IDC_CHECK_CN_USE_SELECTTEX      1111
#define IDC_CHECK_CN_USE_GLOW_SRC       1112
#define IDC_CHECK_CN_USE_GLOW_USR       1113
#define IDC_EDIT_CN_TEXTURE             1114
#define IDC_BUTTON_CN_TEXTURE           1115
#define IDC_EDIT_CN_COLOR_A             1116
#define IDC_EDIT_CN_COLOR_R             1117
#define IDC_EDIT_CN_COLOR_G             1118
#define IDC_EDIT_CN_COLOR_B             1119
#define IDC_BUTTON_CN_COLOR             1120
#define IDC_CHECK_CM_USE_1              1121
#define IDC_EDIT_CM_TEXTURE_1           1122
#define IDC_BUTTON_CM_TEXTURE_1         1123
#define IDC_BUTTON_CM_COLOR_1           1124
#define IDC_EDIT_CM_COLOR_A_1           1125
#define IDC_EDIT_CM_COLOR_R_1           1126
#define IDC_EDIT_CM_COLOR_G_1           1127
#define IDC_EDIT_CM_COLOR_B_1           1128
#define IDC_EDIT_CM_TEX_X_1             1129
#define IDC_EDIT_CM_TEX_Y_1             1130
#define IDC_EDIT_CM_TEXUV_X_1           1131
#define IDC_EDIT_CM_TEXUV_Y_1           1132
#define IDC_CHECK_CM_USE_2              1133
#define IDC_EDIT_CM_TEXTURE_2           1134
#define IDC_BUTTON_CM_TEXTURE_2         1135
#define IDC_BUTTON_CM_COLOR_2           1136
#define IDC_EDIT_CM_COLOR_A_2           1137
#define IDC_EDIT_CM_COLOR_R_2           1138
#define IDC_EDIT_CM_COLOR_G_2           1139
#define IDC_EDIT_CM_COLOR_B_2           1140
#define IDC_EDIT_CM_TEX_X_2             1141
#define IDC_EDIT_CM_TEX_Y_2             1142
#define IDC_EDIT_CM_TEXUV_X_2           1143
#define IDC_EDIT_CM_TEXUV_Y_2           1144
#define IDC_COMBO_CM_BLEND              1145
#define IDC_COMBO_CRF_COLOROP           1146
#define IDC_EDIT_CRF_COLOR_A            1147
#define IDC_EDIT_CRF_COLOR_R            1148
#define IDC_EDIT_CRF_COLOR_G            1149
#define IDC_EDIT_CRF_COLOR_B            1150
#define IDC_EDIT_CRF_TEXTURE            1151
#define IDC_BUTTON_CRF_COLOR            1152
#define IDC_CHECK_CA_USE_ALLTIME        1154
#define IDC_CHECK_CA_USE_TEXCOLOR       1156
#define IDC_CHECK_CMT_USE_1             1162
#define IDC_CHECK_CMT_USE_2             1163
#define IDC_BUTTON_CMT_TEXTURE_1        1164
#define IDC_EDIT_CMT_TEXTURE_1          1165
#define IDC_EDIT_CMT_COLOR_A_1          1166
#define IDC_BUTTON_CMT_COLOR_1          1167
#define IDC_BUTTON_CMT_TEXTURE_2        1168
#define IDC_BUTTON_CMT_COLOR_2          1169
#define IDC_EDIT_CMT_COLOR_R_1          1170
#define IDC_EDIT_CMT_COLOR_G_1          1171
#define IDC_EDIT_CMT_COLOR_B_1          1172
#define IDC_EDIT_CMT_TEX_X_1            1173
#define IDC_EDIT_CMT_TEX_Y_1            1174
#define IDC_EDIT_CMT_TEXUV_X_1          1175
#define IDC_EDIT_CMT_TEXUV_Y_1          1176
#define IDC_EDIT_CMT_TEXTURE_2          1177
#define IDC_EDIT_CMT_COLOR_A_2          1178
#define IDC_EDIT_CMT_COLOR_R_2          1179
#define IDC_EDIT_CMT_COLOR_G_2          1180
#define IDC_EDIT_CMT_COLOR_B_2          1181
#define IDC_EDIT_CMT_TEX_X_2            1182
#define IDC_EDIT_CMT_TEX_Y_2            1183
#define IDC_EDIT_CMT_TEXUV_X_2          1184
#define IDC_EDIT_CMT_TEXUV_Y_2          1185
#define IDC_COMBO_CMT_BLEND             1186
#define IDC_CHECK_CMT_USE_TEXMAP        1187
#define IDC_BUTTON_CMT_TEXMAP           1188
#define IDC_EDIT_CMT_TEXMAP             1189
#define IDC_CHECK_CMT_USE_ALLTEX        1190
#define IDC_CHECK_CMT_USE_SELECTTEX     1191
#define IDC_COMBO_CGH_ANI_M             1193
#define IDC_COMBO_CGH_ANI_S             1194
#define IDC_EDIT_CGH_COLOR_A            1195
#define IDC_EDIT_CGH_COLOR_R            1196
#define IDC_EDIT_CGH_COLOR_G            1197
#define IDC_EDIT_CGH_COLOR_B            1198
#define IDC_EDIT_CGH_NUM                1199
#define IDC_EDIT_CGH_UNIT               1200
#define IDC_EDIT_CGH_ALPHA              1201
#define IDC_BUTTON_CGH_COLOR            1202
#define IDC_COMBO_CS2_COLOROP           1203
#define IDC_EDIT_CS2_COLOR_A            1204
#define IDC_EDIT_CS2_COLOR_R            1205
#define IDC_EDIT_CS2_COLOR_G            1206
#define IDC_EDIT_CS2_COLOR_B            1207
#define IDC_BUTTON_CS2_COLOR            1208
#define IDC_CHECK_CS2_CUBEMAP           1209
#define IDC_EDIT_CTN_SIZE               1213
#define IDC_EDIT_CTN_ADDSIZE            1214
#define IDC_EDIT_CTN_TEX                1215
#define IDC_EDIT_CTN_OBLIQUE            1216
#define IDC_CHECK_CTN_USE_OBLIQUE       1217
#define IDC_BUTTON_CTN_TEX              1218
#define IDC_BUTTON_CTN_OBLIQUE          1219
#define IDC_CHECK_CTD_USE_UPDOWN        1219
#define IDC_EDIT_CTD_SPEED              1220
#define IDC_COMBO_CTD_INTENSITY         1221
#define IDC_EDIT_CPT_PARTICLEPERSEC     1222
#define IDC_EDIT_CPT_RANDOMRANGE        1223
#define IDC_CHECK_CPT_RANDOMRANGE       1224
#define IDC_EDIT_CPT_LIFE_MIN           1225
#define IDC_EDIT_CPT_LIFE_MAX           1226
#define IDC_EDIT_CPT_SCALE_X            1227
#define IDC_EDIT_CPT_SCALE_Y            1228
#define IDC_EDIT_CPT_SCALE_Z            1229
#define IDC_CHECK_CPT_ROTATE            1230
#define IDC_CHECK_CPT_SEQUENCE          1231
#define IDC_CHECK_CPT_REMAIN            1232
#define IDC_EDIT_CBP_VELO_X             1232
#define IDC_EDIT_CPT_ROTATE_MIN         1233
#define IDC_EDIT_CPT_COL                1234
#define IDC_EDIT_CPT_VEL_MIN            1235
#define IDC_EDIT_CBP_VELO_Y             1235
#define IDC_BUTTON_CPT_TEXTURE          1236
#define IDC_EDIT_CBP_VELO_Z             1236
#define IDC_EDIT_CPT_TEXTURE            1237
#define IDC_BUTTON_CBP_TEXTURE          1237
#define IDC_EDIT_CPT_ROTATE_MAX         1238
#define IDC_EDIT_CPT_ROW                1239
#define IDC_EDIT_CPT_VEL_MAX            1240
#define IDC_EDIT_CBP_TEXTURE            1240
#define IDC_EDIT_CPT_COLOR_A            1241
#define IDC_EDIT_CPT_COLOR_R            1242
#define IDC_EDIT_CPT_COLOR_G            1243
#define IDC_EDIT_CPT_COLOR_B            1244
#define IDC_BUTTON_CPT_COLOR            1245
#define IDC_BUTTON_CPT_LIST_ADD         1246
#define IDC_EDIT_CBP_BONE               1246
#define IDC_BUTTON_CPT_LIST_DEL         1247
#define IDC_BUTTON_CBP_SELBONE          1247
#define IDC_BUTTON_CPT_LIST_UP          1248
#define IDC_EDIT_CBP_OFFSET_X           1248
#define IDC_BUTTON_CPT_LIST_DOWN        1249
#define IDC_EDIT_CBP_OFFSET_Y           1249
#define IDC_LIST_POS                    1250
#define IDC_EDIT_CBP_OFFSET_Z           1250
#define IDC_BUTTON_CPT_LIST_APPLY       1251
#define IDC_CHECK_CBP_USE_OFFSET        1251
#define IDC_BUTTON_CBL_LIST_EDIT        1251
#define IDC_EDIT_CBP_PARTICLEPERSEC     1252
#define IDC_BUTTON_CPT_LIST_EDIT        1252
#define IDC_EDIT_CBP_CREATELENGTH       1253
#define IDC_EDIT_CBP_LIFE_MIN           1254
#define IDC_EDIT_CBP_LIFE_MAX           1255
#define IDC_EDIT_CBP_SCALE_X            1256
#define IDC_EDIT_CBP_SCALE_Y            1257
#define IDC_EDIT_CBP_SCALE_Z            1258
#define IDC_EDIT_CBP_ROTATE_MIN         1259
#define IDC_EDIT_CBP_ROTATE_MAX         1260
#define IDC_EDIT_CBP_COL                1261
#define IDC_EDIT_CBP_ROW                1262
#define IDC_EDIT_CBP_COLOR_A            1263
#define IDC_EDIT_CBP_COLOR_R            1264
#define IDC_EDIT_CBP_COLOR_G            1265
#define IDC_EDIT_CBP_COLOR_B            1266
#define IDC_BUTTON_CBP_COLOR            1267
#define IDC_CHECK_CBP_ROTATE            1268
#define IDC_CHECK_CBP_SEQUENCE          1269
#define IDC_CHECK_CBP_USE_REMAIN        1270
#define IDC_EDIT_CBL_PARTICLEPERSEC     1270
#define IDC_BUTTON_CBP_GETOFFSET        1271
#define IDC_EDIT_CBL_CREATELENGTH       1271
#define IDC_BUTTON_CBP_RESETOFFSET      1272
#define IDC_EDIT_CBL_LIFE_MIN           1272
#define IDC_EDIT_CLB_SHAKE              1272
#define IDC_BUTTON_CBP_EDITOFFSET       1273
#define IDC_EDIT_CBL_LIFE_MAX           1273
#define IDC_EDIT_CLB_SCALE_X            1273
#define IDC_EDIT_CBL_SCALE_X            1274
#define IDC_EDIT_CLB_SCALE_Y            1274
#define IDC_EDIT_CBL_SCALE_Y            1275
#define IDC_EDIT_CLB_SCALE_Z            1275
#define IDC_EDIT_CBL_SCALE_Z            1276
#define IDC_EDIT_CLB_X_AXIS_X           1276
#define IDC_EDIT_CBL_ROTATE_MIN         1277
#define IDC_EDIT_CLB_X_AXIS_Y           1277
#define IDC_EDIT_CBL_ROTATE_MAX         1278
#define IDC_EDIT_CLB_Y_AXIS_X           1278
#define IDC_EDIT_CBL_COL                1279
#define IDC_EDIT_CLB_Y_AXIS_Y           1279
#define IDC_EDIT_CBL_ROW                1280
#define IDC_EDIT_CLB_Y_AXIS_Z           1280
#define IDC_EDIT_CBL_VEL_MIN            1281
#define IDC_EDIT_CLB_LIFE_MIN           1281
#define IDC_EDIT_CBL_VEL_MAX            1282
#define IDC_EDIT_CLB_LIFE_MAX           1282
#define IDC_EDIT_CBL_TEXTURE            1283
#define IDC_EDIT_CLB_SEQ_COL            1283
#define IDC_EDIT_CBL_COLOR_A            1284
#define IDC_EDIT_CLB_SEQ_ROW            1284
#define IDC_EDIT_CBL_COLOR_R            1285
#define IDC_EDIT_CLB_TEXTURE1           1285
#define IDC_EDIT_CBL_COLOR_G            1286
#define IDC_EDIT_CLB_TEXTURE2           1286
#define IDC_EDIT_CBL_COLOR_B            1287
#define IDC_EDIT_CLB_COLOR_1_A          1287
#define IDC_CHECK_CBL_ROTATE            1288
#define IDC_EDIT_CLB_COLOR_1_R          1288
#define IDC_CHECK_CBL_SEQUENCE          1289
#define IDC_EDIT_CLB_COLOR_1_G          1289
#define IDC_CHECK_CBL_REMAIN            1290
#define IDC_EDIT_CLB_COLOR_1_B          1290
#define IDC_BUTTON_CBL_TEXTURE          1291
#define IDC_BUTTON_CBL_COLOR            1292
#define IDC_BUTTON_CLB_TEXTURE2         1292
#define IDC_BUTTON_CBL_LIST_ADD         1293
#define IDC_BUTTON_CLB_COLOR1           1293
#define IDC_BUTTON_CBL_LIST_UP          1294
#define IDC_EDIT_CLB_COLOR_2_A          1294
#define IDC_BUTTON_CBL_LIST_DOWN        1295
#define IDC_EDIT_CLB_COLOR_2_R          1295
#define IDC_BUTTON_CBL_LIST_DEL         1296
#define IDC_EDIT_CLB_COLOR_2_G          1296
#define IDC_CHECK_EDITPOS_USEOFFSET     1297
#define IDC_EDIT_CLB_COLOR_2_B          1297
#define IDC_EDIT_EDITPOS_OFFSET_X       1298
#define IDC_BUTTON_CLB_COLOR2           1298
#define IDC_EDIT_EDITPOS_OFFSET_Y       1299
#define IDC_EDIT_CLB_DISTANCE_MIN       1299
#define IDC_EDIT_CLB_DISTANCE_MAX       1300
#define IDC_BUTTON_EDITPOS_RESET        1301
#define IDC_EDIT_CLB_TEXROTATE_MIN      1301
#define IDC_BUTTON_EDITPOS_SAVE         1302
#define IDC_EDIT_CLB_TEXROTATE_MAX      1302
#define IDC_EDIT_EDITPOS_OFFSET_Z       1303
#define IDC_BUTTON_CUC_COLOR            1304
#define IDC_EDIT_CUC_COLOR_A            1305
#define IDC_EDIT_CUC_COLOR_R            1306
#define IDC_EDIT_CUC_COLOR_G            1307
#define IDC_EDIT_CUC_COLOR_B            1308
#define IDC_CHECK_CLB_USE_SEQ           1309
#define IDC_CHECK_CLB_CAMMOVE           1310
#define IDC_CHECK_CLB_USE_SEQ2          1310
#define IDC_CHECK_CUC_FLAG_USE_COLOR_2  1310
#define IDC_COMBO_CLB_COLOR_2_TYPE      1311
#define IDC_EDIT_CLB_BONE2              1312
#define IDC_EDIT_CLB_BONE1              1313
#define IDC_BUTTON_CLB_BONE_1           1314
#define IDC_BUTTON_CLB_BONE_2           1315
#define IDC_BUTTON_CLB_INSERT           1316
#define IDC_BUTTON_CLB_DELETE           1317
#define IDC_EDIT_CLB_PARTICLEPERSEC     1318
#define IDC_EDIT_CLB_CREATELENGTH       1319
#define IDC_BUTTON_CLB_TEXTURE1         1320
#define IDC_EDIT_CAR_LIFE_MIN           1321
#define IDC_EDIT_CAR_LIFE_MAX           1322
#define IDC_EDIT_CAR_REPLAY_MIN         1323
#define IDC_EDIT_CAR_REPLAY_MAX         1324
#define IDC_EDIT_CAR_X_SIZE_X           1325
#define IDC_EDIT_CAR_X_SIZE_Y           1326
#define IDC_EDIT_CAR_Y_SIZE_X           1327
#define IDC_EDIT_CAR_Y_SIZE_Y           1328
#define IDC_EDIT_CAR_TEXSPEED_MIN       1329
#define IDC_EDIT_CAR_TEXSPEED_MAX       1330
#define IDC_EDIT_CAR_SEQ_COL            1331
#define IDC_EDIT_CAR_SEQ_ROW            1332
#define IDC_EDIT_CAR_TEXTURE            1333
#define IDC_EDIT_CAR_COLOR_A            1334
#define IDC_EDIT_CAR_COLOR_R            1335
#define IDC_EDIT_CAR_COLOR_G            1336
#define IDC_EDIT_CAR_COLOR_B            1337
#define IDC_CHECK_CAR_USE_SEQ           1338
#define IDC_BUTTON_CAR_TEXTURE          1339
#define IDC_BUTTON_CAR_COLOR            1340
#define IDC_EDIT_CAR_EDIT_POS_X         1341
#define IDC_EDIT_CAR_EDIT_POS_Y         1342
#define IDC_EDIT_CAR_EDIT_POS_Z         1343
#define IDC_EDIT_CAR_EDIT_BONE          1344
#define IDC_EDIT_CAR_EDIT_MESHDIST      1345
#define IDC_BUTTON_CAR_EDIT_BONE        1346
#define IDC_BUTTON_CAR_EDIT_POS         1347
#define IDC_BUTTON_CAR_EDIT_INSERT      1348
#define IDC_BUTTON_CAR_EDIT_DELETE      1349
#define IDC_BUTTON_CTD_TEXTURE          1349
#define IDC_EDIT_CAR_EDIT_NORM_X        1350
#define IDC_EDIT_CTD_TEXTURE            1350
#define IDC_EDIT_CAR_EDIT_NORM_Y        1351
#define IDC_CHECK_CS2_USE_CUBE          1351
#define IDC_CHECK_CS2_USE_CUBETEXTURE   1351
#define IDC_EDIT_CAR_EDIT_POS_Z2        1352
#define IDC_EDIT_CAR_EDIT_NORM_Z        1352
#define IDC_BUTTON_CS2_TEXTURE          1352
#define IDC_EDIT_CS2_CUBETEXTURE        1353
#define IDC_CHECK_CUC_FLAG_USE_COLOR_1  1354
#define ID_VIEW_EDITORTOOLBAR           32771
#define ID_BUTTON32772                  32772
#define ID_FILE_SAVE2                   32773
#define ID_BUTTON32774                  32774
#define ID_BUTTON32775                  32775
#define ID_FILE_SAVEOLD                 32776
#define ID_BUTTON32777                  32777
#define ID_BUTTON32778                  32778
#define ID_RENDER_RENDERTRACE           32779
#define ID_RENDER_RENDERPLANE           32780
#define ID_COLLISIONTYPE_TYPE1          32781
#define ID_COLLISIONTYPE_TYPE2          32782
#define ID_COLLISIONTYPE_TYPE3          32783
#define ID_ITEMLEVEL_LEVEL5             32784
#define ID_ITEMLEVEL_LEVEL4             32785
#define ID_ITEMLEVEL_LEVEL3             32786
#define ID_ITEMLEVEL_LEVEL2             32787
#define ID_ITEMLEVEL_LEVEL1             32788
#define ID_ITEMLEVEL_LEVEL0             32789
#define ID_ITEMLEVEL_LEVEL6             32790
#define ID_ITEMLEVEL_LEVEL7             32791
#define ID_ITEMLEVEL_LEVEL8             32792
#define ID_ITEMLEVEL_LEVEL9             32793
#define ID_ITEMLEVEL_LEVEL10            32794
#define ID_ITEMLEVEL_LEVEL11            32795
#define ID_ITEMLEVEL_00                 32796
#define ID_ITEMLEVEL_01                 32797
#define ID_ITEMLEVEL_02                 32798
#define ID_ITEMLEVEL_03                 32799
#define ID_ITEMLEVEL_04                 32800
#define ID_ITEMLEVEL_05                 32801
#define ID_ITEMLEVEL_06                 32802
#define ID_ITEMLEVEL_07                 32803
#define ID_ITEMLEVEL_08                 32804
#define ID_ITEMLEVEL_09                 32805
#define ID_ITEMLEVEL_10                 32806
#define ID_ITEMLEVEL_11                 32807
#define ID_ITEMLEVEL_OFF                32808
#define ID_RENDER_RENDERDEBUGINFO       32809
#define ID_CAMERA_RESETCAMERAPOS        32810
#define ID_COLLISIONTYPE_TYPE_1         32811
#define ID_COLLISIONTYPE_TYPE_2         32812
#define ID_COLLISIONTYPE_TYPE_3         32813
#define ID_FILE_NEW32814                32814
#define ID_CURSORCONTROL_MATRIXMOVE     32815
#define ID_CURSORCONTROL_MATRIX         32816
#define ID_CURSORCONTROL_MATRIX32817    32817
#define ID_EDIT_MATRIX_MOVE             32818
#define ID_EDIT_MATRIX_ROTATE           32819
#define ID_EDIT_MATRIX_SCALE            32820
#define ID_FILE_SAVEEFFSKIN             32821

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        311
#define _APS_NEXT_COMMAND_VALUE         32822
#define _APS_NEXT_CONTROL_VALUE         1355
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
