//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EditorMobNpc.rc
//
#define ID_LOAD_MNSF                    3
#define ID_SAVE_MNSF                    4
#define ID_LOAD_CSV                     5
#define ID_SAVE_CSV                     6
#define ID_SEARCH                       7
#define ID_DIVIDE                       8
#define ID_DIVIDE_HP                    8
#define ID_DIVIDE_HP2                   9
#define ID_DIVIDE_DAMAGE                9
#define IDD_EDITORMOBNPC_DIALOG         102
#define IDD_EDIT1                       103
#define IDD_EDIT2                       104
#define IDD_TREE                        105
#define IDR_MAINFRAME                   128
#define IDR_MENU_EDIT                   129
#define IDD_DIALOG_SEARCH               130
#define IDD_DIALOG_CROW                 131
#define IDD_DIALOG_ITEM                 132
#define IDD_DIALOG_SKILL                133
#define IDC_STATIC_TOOL                 1000
#define IDC_EDIT_MID                    1000
#define IDC_EDIT_SID                    1001
#define IDC_STATIC_BLOW_OPTION1         1001
#define IDC_EDIT_NAME                   1002
#define IDC_STATIC_BLOW_OPTION2         1002
#define IDC_BUTTON_PAGE_NEXT            1003
#define IDC_BUTTON_PAGE_BACK            1003
#define IDC_EDIT_NAME2                  1004
#define IDC_TREE                        1005
#define IDC_BUTTON_SEARCH               1005
#define IDC_COMBO_TRIBE                 1005
#define IDC_COMBO_CROW                  1006
#define IDC_COMBO_BRIGHT                1007
#define IDC_LIST_RESULT                 1008
#define IDC_COMBO_PET                   1008
#define IDC_COMBO_GATHER_ANI            1009
#define IDC_COMBO_SEARCHTYPE            1010
#define IDC_CHECK_OVERLAPATTACK         1010
#define IDC_COMBO_TYPE                  1011
#define IDC_EDIT_HP                     1011
#define IDC_EDIT_LEVEL                  1012
#define IDC_EDIT_SEARCH                 1013
#define IDC_EDIT_GENTIME                1013
#define IDC_BUTTON_GO                   1014
#define IDC_EDIT_MP                     1014
#define IDC_EDIT_SP                     1015
#define IDC_EDIT_HP_REC                 1016
#define IDC_LIST_PATTERN                1016
#define IDC_EDIT_MP_REC                 1017
#define IDC_EDIT_SP_REC                 1018
#define IDC_EDIT_DEF                    1019
#define IDC_EDIT_AVOIDRATE              1020
#define IDC_EDIT_HITRATE                1021
#define IDC_EDIT_SEL_MID                1021
#define IDC_EDIT_VIEWDISTANCE           1022
#define IDC_EDIT_SEL_SID                1022
#define IDC_EDIT_ADDEXP                 1023
#define IDC_EDIT_SEL_NAME               1023
#define IDC_EDIT_RES_FIRE               1024
#define IDC_EDIT_RES_ICE                1025
#define IDC_LIST_SELECT                 1025
#define IDC_EDIT_RES_POI                1026
#define IDC_EDIT_RES_ELECT              1027
#define IDC_EDIT_RES_SPIRIT             1028
#define IDC_EDIT_GATHER_TIME_LOW        1029
#define IDC_STATIC_SEARCH_1             1030
#define IDC_EDIT_GATHER_TIME_HIGH       1030
#define IDC_EDIT_GATHER_RATE            1031
#define IDC_STATIC_SEARCH_3             1032
#define IDC_EDIT_SKINFILE               1032
#define IDC_BUTTON_SKINFILE             1033
#define IDC_EDIT_TALKFILE               1034
#define IDC_BUTTON_TALKFILE             1035
#define IDC_EDIT_SALEFILE_00            1036
#define IDC_EDIT_SALEFILE_01            1037
#define IDC_EDIT_SALEFILE_02            1038
#define IDC_BUTTON_CROWSALE_01          1039
#define IDC_BUTTON_CROWSALE_00          1040
#define IDC_BUTTON_CROWSALE_02          1041
#define IDC_EDIT_BIRTHEFFECT            1042
#define IDC_BUTTON_BIRTHEFFECT          1043
#define IDC_EDIT_BODYRADIUS             1044
#define IDC_EDIT_WALKSPEED              1045
#define IDC_CHECK_RUN                   1046
#define IDC_EDIT_RUNSPEED               1047
#define IDC_BUTTON_MOBLINK              1048
#define IDC_EDIT_MOBLINK_MID            1049
#define IDC_EDIT_MOBLINK_SID            1050
#define IDC_EDIT_MOBLINK_NAME           1051
#define IDC_BUTTON_MOBLINK_CHECK        1052
#define IDC_EDIT_DEATHEFFECT            1052
#define IDC_EDIT_MOBLINK_SCALE          1053
#define IDC_EDIT_MOBLINK_DELAY          1054
#define IDC_EDIT_GEN_ITEM               1055
#define IDC_BUTTON_ITEMGEN              1056
#define IDC_EDIT_GEN_QITEM              1057
#define IDC_BUTTON_ITEMGENQ             1058
#define IDC_BUTTON_GENITEM              1059
#define IDC_EDIT_GEN_ITEM_MID           1060
#define IDC_EDIT_ATTACK                 1060
#define IDC_EDIT_GEN_ITEM_SID           1061
#define IDC_BUTTON_ATTACK_MINUS         1061
#define IDC_EDIT_GEN_ITEM_NAME          1062
#define IDC_BUTTON_ATTACK_ADD           1062
#define IDC_BUTTON_CHECK_GENITEM        1063
#define IDC_EDIT_PATTERN_NUM            1063
#define IDC_EDIT_BLOWEFFECT             1063
#define IDC_EDIT_GEN_ITEM_RATE          1064
#define IDC_COMBO_PATTERN_ACTION        1064
#define IDC_EDIT_GEN_MONEY_VALUE        1065
#define IDC_EDIT_PATTERN_DNRATE         1065
#define IDC_EDIT_GEN_MONEY_RATE         1066
#define IDC_EDIT_PATTERN_ATTACKSET      1066
#define IDC_CHECK_EMFLAG_TARSHORT       1067
#define IDC_BUTTON_PATTERN_SAVE         1067
#define IDC_CHECK_EMFLAG_CDCERTIFY      1068
#define IDC_BUTTON_PATTERN_ADD          1068
#define IDC_CHECK_EMFLAG_INVISIBLE      1069
#define IDC_BUTTON_PATTERN_EDIT         1069
#define IDC_CHECK_EMFLAG_RECINVISIBLE   1070
#define IDC_BUTTON_PATTERN_DELETE       1070
#define IDC_BUTTON_PAGE_CANCEL          1071
#define IDC_CHECK_EMFLAG_BARRIER        1072
#define IDC_CHECK_ATTACK_USE            1072
#define IDC_CHECK_EMFLAG_POSHOLD        1073
#define IDC_COMBO_ATTACK_TYPE           1073
#define IDC_CHECK_EMFLAG_DIRHOLD        1074
#define IDC_EDIT_ATTACK_RANGE           1074
#define IDC_CHECK_EMFLAG_KNOCK          1075
#define IDC_EDIT_ATTACK_DAMAGELOW       1075
#define IDC_CHECK_EMFLAG_BOSS           1076
#define IDC_EDIT_ATTACK_DAMAGEHIGH      1076
#define IDC_CHECK_EMFLAG_BUSUNIT        1077
#define IDC_EDIT_ATTACK_DELAY           1077
#define IDC_CHECK_EMFLAG_IGNORESHOCK    1078
#define IDC_EDIT_ATTACK_SPUSAGE         1078
#define IDC_CHECK_EMFLAG_AUTODROPOUT    1079
#define IDC_EDIT_ATTACK_SKILL_MID       1079
#define IDC_EDIT_LIVETIME               1080
#define IDC_EDIT_ATTACK_SKILL_SID       1080
#define IDC_BUTTON_ATTACK_SKILL         1081
#define IDC_BUTTON_DEATHEFFECT          1081
#define IDC_BUTTON_CHECK_SKILL          1082
#define IDC_BUTTON_BIRTHEFFECT3         1082
#define IDC_BUTTON_BLOWEFFECT           1082
#define IDC_EDIT_ATTACK_SKILL_NAME      1083
#define IDC_COMBO_SU                    1083
#define IDC_COMBO_SUMMON                1083
#define IDC_EDIT_ATTACK_SKILL_LEVEL     1084
#define IDC_COMBO_NPCTYPE               1084
#define IDC_COMBO_ATTACK_SKILL_TARGET   1085
#define IDC_EDIT_ADDEXP2                1085
#define IDC_EDIT_ADDCP                  1085
#define IDC_BUTTON_SELFBODY             1086
#define IDC_CHECK_EMFLAG_IGNORESHOCK2   1086
#define IDC_CHECK_MOBLINK_ENABLE        1086
#define IDC_EDIT_ATTACK_SELFBODY        1087
#define IDC_BUTTON_NPCSHOP              1087
#define IDC_BUTTON_TARGETBODY           1088
#define IDC_EDIT_SALEFILE_3             1088
#define IDC_EDIT_NPCSHOP                1088
#define IDC_EDIT_ATTACK_TARGETBODY      1089
#define IDC_EDIT_GEN_MONEY_LUCK_RATE    1089
#define IDC_BUTTON_TARGET               1090
#define IDC_EDIT_GEN_MONEY_LUCK_MAX     1090
#define IDC_BUTTON_PAGE_SAVE            1091
#define IDC_EDIT_ATTACK_TARGET          1092
#define IDC_CHECK_OVERLAPATTACK2        1092
#define IDC_CHECK_HIDENAME              1092
#define IDC_LIST_ANIM                   1093
#define IDC_BUTTON_NPC_ITEM_EXCHANGE    1093
#define IDC_EDIT_ANI_MAIN               1094
#define IDC_EDIT_NPCSHOP2               1094
#define IDC_EDIT_NPC_ITEM_EXCHANGE      1094
#define IDC_EDIT_ANI_SUB                1095
#define IDC_CHECK_NOTICE_RESPAWN        1095
#define IDC_EDIT_ANI_TIME_START         1096
#define IDC_CHECK_NOTICE_RESPAWN2       1096
#define IDC_EDIT_ANI_TIME_END           1097
#define IDC_CHECK_NOTICE_DEFEAT         1097
#define IDC_EDIT_ANI_TIME_UNIT          1098
#define IDC_CHECK_EMFLAG_IGNORESHOCK6   1098
#define IDC_CHECK_NOTICE_DEFEAT2        1098
#define IDC_EDIT_ANI_FLAGS              1099
#define IDC_CHECK_DUMMY_1               1099
#define IDC_EDIT_ANI_DIV                1100
#define IDC_CHECK_HIDENAME3             1100
#define IDC_CHECK_DUMMY_2               1100
#define IDC_LIST_ANI_DIV                1101
#define IDC_COMBO_CTFTYPE               1101
#define IDC_EDIT_ANI_NAME               1102
#define IDC_BUTTON_USE_ANI              1103
#define IDC_CHECK_DEATH_NOBODY          1104
#define IDC_EDIT_ANI_SUB2               1105
#define IDC_EDIT1                       1105
#define IDC_EDIT_DUMMY_0                1105
#define IDC_COMBO_SEARCH                1125
#define IDC_COMBO_BLOW_TYPE             1128
#define IDC_EDIT_BLOW_TIME              1129
#define IDC_EDIT_BLOW_CHANCE            1130
#define IDC_EDIT_BLOW_VAR1              1131
#define IDC_EDIT_BLOW_VAR2              1132
#define ID_TOOL_ADD                     32771
#define ID_TOOL_DELETE                  32773
#define ID_TOOL_COPY                    32774
#define ID_TOOL_PASTE_VAL               32777
#define ID_TOOL_PASTE_NEW               32778
#define ID_TOOL_EDIT1                   32779
#define ID_TOOL_EDIT2                   32781

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1106
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
