//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EditorLevel.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_EditorLevelTYPE             130
#define IDD_DLG_FIND_SKILL              155
#define IDD_DLG_FIND_QUEST              159
#define IDD_DLG_FIND_ITEM               169
#define IDD_PAGE_MAIN                   181
#define IDD_DLG_FIND_CROW               187
#define IDD_DLG_MAIN                    310
#define IDD_PAGE_BASIC                  311
#define IDD_PAGE_CROW                   312
#define IDD_PAGE_CONDITION              313
#define IDD_DLG_CROW_REPLACE            314
#define IDD_PAGE_EFF                    315
#define IDD_PAGE_GATE                   316
#define IDD_PAGE_LM                     317
#define IDD_PAGE_ETCH                   318
#define IDD_PAGE_EDIT_GATE              319
#define IDD_PAGE_EDIT_CROW              320
#define IDD_PAGE_EDIT_EFFECT            321
#define IDD_PAGE_EDIT_LANDMARK          322
#define IDD_DLG_FIND_MAP                323
#define IDD_DLG_SET_LEADER              324
#define IDD_DLG_SET_MEMBER              325
#define IDC_STATIC_TOOL                 1000
#define IDC_COMBO_PAGE                  1002
#define IDC_BUTTON_OPEN                 1003
#define IDC_EDIT_WLDFILE                1004
#define IDC_BUTTON_WLD                  1005
#define IDC_EDIT_LEVFILE                1006
#define IDC_COMBO_QUAD                  1007
#define IDC_BUTTON_QUAD                 1009
#define IDC_BUTTON_REQLEVEL             1010
#define IDC_BUTTON_REQITEM              1011
#define IDC_BUTTON_REQSKILL             1012
#define IDC_BUTTON_REQCOMQUEST          1013
#define IDC_BUTTON_REQACTQUEST          1014
#define IDC_BUTTON_REQLIFE              1015
#define IDC_BUTTON_REQBRIGHT            1016
#define IDC_LIST                        1016
#define IDC_EDIT_REQITEM_MID            1017
#define IDC_EDIT_REQITEM_SID            1018
#define IDC_EDIT_REQSKILL_MID           1019
#define IDC_EDIT_REQSKILL_SID           1020
#define IDC_EDIT_REQCOMQUESTID          1021
#define IDC_EDIT_REQACTQUESTID          1022
#define IDC_EDIT_REQITEM_NAME           1023
#define IDC_EDIT_REQSKILL_NAME          1024
#define IDC_EDIT_REQCOMQUEST_NAME       1025
#define IDC_EDIT_REQACTQUEST_NAME       1026
#define IDC_COMBO_REQLEVEL              1027
#define IDC_EDIT_REQLEVEL_LOW           1028
#define IDC_EDIT_REQLEVEL_HIGH          1029
#define IDC_COMBO_REQLIFE               1030
#define IDC_EDIT_REQLIFE                1031
#define IDC_BUTTON_REQITEM_REMOVE       1032
#define IDC_COMBO_REQBRIGHT             1033
#define IDC_EDIT_REQBRIGHT              1034
#define IDC_CHECK_PARTYMEMBER           1035
#define IDC_BUTTON_REQSKILL_REMOVE      1036
#define IDC_BUTTON_REQCOMQUEST_REMOVE   1037
#define IDC_BUTTON_REQACTQUEST_REMOVE   1038
#define IDC_BUTTON_SAVE                 1039
#define IDC_BUTTON_CLOSE                1040
#define IDC_EDIT_SHOWMID                1040
#define IDC_BUTTON_RESET                1041
#define IDC_EDIT_SHOWSID                1041
#define IDC_BUTTON_EFF_ADD              1041
#define IDC_BUTTON_APPLY                1041
#define IDC_BUTTON_EFF_EDIT             1042
#define IDC_BUTTON_REGNEW               1042
#define IDC_BUTTON_REQ_ACT_P            1042
#define IDC_BUTTON_SHOWFIND             1043
#define IDC_BUTTON_EFF_DELETE           1043
#define IDC_BUTTON_MOUSEPOS             1043
#define IDC_BUTTON_RESTORE              1043
#define IDC_BUTTON_REBUILD              1043
#define IDC_COMBO_REQ_ACT_P             1043
#define IDC_EDIT_REQ_ACT_P              1044
#define IDC_BUTTON_NEW                  1045
#define IDC_BUTTON_REQ_CON_P            1045
#define IDC_BUTTON_EDIT                 1046
#define IDC_BUTTON_ACTION_ADD           1046
#define IDC_COMBO_REQ_CON_P             1046
#define IDC_BUTTON_OK                   1047
#define IDC_BUTTON_DELETE               1047
#define IDC_BUTTON_ACTION_EDIT          1047
#define IDC_EDIT_REQBRIGHT3             1047
#define IDC_EDIT_REQ_CON_P              1047
#define IDC_BUTTON_OK2                  1048
#define IDC_BUTTON_REBUILDNAME          1048
#define IDC_BUTTON_ACTION_DEL           1048
#define IDC_BUTTON_REPLACEID            1049
#define IDC_BUTTON_COPY                 1050
#define IDC_EDIT_COPY                   1051
#define IDC_BUTTON_PASTENEW             1052
#define IDC_BUTTON_SHOW_ALL             1053
#define IDC_BUTTON_SHOW_NPC             1054
#define IDC_BUTTON_SHOW_INVALID         1055
#define IDC_BUTTON_DELETE2              1055
#define IDC_BUTTON_SHOWFIND_CLEAR       1056
#define IDC_BUTTON_CROW_FROM            1056
#define IDC_EDIT_CROW_MID_FROM          1057
#define IDC_BUTTON_CLEAR                1057
#define IDC_EDIT_CROW_SID_FROM          1058
#define IDC_BUTTON_MOB_MEMBER           1058
#define IDC_EDIT_CROW_NAME_FROM         1059
#define IDC_BUTTON_MOB_LEADER           1059
#define IDC_EDIT_CROW_MID_TO            1060
#define IDC_BUTTON_CLEAR2               1060
#define IDC_BUTTON_FSCHED               1060
#define IDC_EDIT_CROW_SID_TO            1061
#define IDC_COMBO_SKILL_SEARCH          1062
#define IDC_EDIT_CROW_NAME_TO           1062
#define IDC_EDIT_SKILL_SEARCH           1063
#define IDC_BUTTON_CROW_TO              1063
#define IDC_BUTTON_CROW_ADD             1064
#define IDC_CHECK_MOBCHASE              1065
#define IDC_CHECK_LIMITTIME             1066
#define IDC_EDIT_LIMIT_MINUTE           1067
#define IDC_COMBO_QUEST_SEARCH          1068
#define IDC_EDIT_LIMIT_TERMMINUTE       1068
#define IDC_EDIT_QUEST_SEARCH           1069
#define IDC_CHECK_CONTROLCAM            1069
#define IDC_EDIT_CAM_POSX               1070
#define IDC_COMBO_ITEM_SEARCH           1071
#define IDC_BUTTON_CONTROLCAM           1071
#define IDC_EDIT_ITEM_SEARCH            1072
#define IDC_EDIT_CAM_LEFT               1072
#define IDC_EDIT_CAM_RIGHT              1073
#define IDC_COMBO_EFF_TYPE              1074
#define IDC_EDIT_EFF_NUM                1075
#define IDC_EDIT_CAM_DOWN               1076
#define IDC_EDIT_CAM_UP                 1077
#define IDC_EDIT_CAM_FAR                1078
#define IDC_EDIT_CAM_NEAR               1079
#define IDC_EDIT_CAM_POSY               1080
#define IDC_EDIT_CAM_POSZ               1081
#define IDC_CHECK_LANDEFFECT            1082
#define IDC_STATIC_FILTER_INFO          1083
#define IDC_EDIT_EFF_VAL                1083
#define IDC_BUTTON_EFF_POSSCREEN        1088
#define IDC_BUTTON_EFF_CLOSE            1091
#define IDC_BUTTON_EFF_SAVE             1092
#define IDC_EDIT_GATE_NAME              1092
#define IDC_EDIT_EFFECT_FILE            1093
#define IDC_CHECK_GATE_IN               1094
#define IDC_EDIT_GATE_ID                1095
#define IDC_BUTTON_CHECK                1096
#define IDC_BUTTON_CROW                 1097
#define IDC_CHECK_GATE_OUT              1098
#define IDC_BUTTON_BUS                  1098
#define IDC_EDIT_GATE_TOMAP_MID         1099
#define IDC_EDIT_GATE_TOMAP_SID         1100
#define IDC_EDIT_GATE_TOMAP_NAME        1101
#define IDC_BUTTON_FINDMAP              1102
#define IDC_EDIT_GATE_TOMAP_GATE        1103
#define IDC_COMBO_MAP_SEARCH            1103
#define IDC_EDIT_GATE_GATEINTERVAL_X    1104
#define IDC_EDIT_MAP_SEARCH             1104
#define IDC_EDIT_GATE_GATEINTERVAL_Y    1105
#define IDC_BUTTON_OPENEFFECT           1105
#define IDC_EDIT_EFFECT_NAME            1106
#define IDC_EDIT_LM_NAME                1107
#define IDC_EDIT_CROW_MID               1107
#define IDC_EDIT_CROW_SID               1108
#define IDC_EDIT_CROW_NAME              1109
#define IDC_EDIT_GENTIME                1110
#define IDC_EDIT_GENMIN                 1111
#define IDC_EDIT_GENHOUR                1112
#define IDC_CHECK_DAYOFWEEK_0           1113
#define IDC_CHECK_DAYOFWEEK_1           1114
#define IDC_CHECK_DAYOFWEEK_2           1115
#define IDC_CHECK_DAYOFWEEK_3           1116
#define IDC_CHECK_DAYOFWEEK_4           1117
#define IDC_CHECK_DAYOFWEEK_5           1118
#define IDC_CHECK_DAYOFWEEK_6           1119
#define IDC_CHECK_GENPOS_RANDOM         1120
#define IDC_EDIT_GENPOS_NUM             1121
#define IDC_EDIT_GENPOS_DISTANCE        1122
#define IDC_CHECK_GROUP_LEADER          1123
#define IDC_EDIT_GROUP_NAME             1124
#define IDC_EDIT_BUS                    1125
#define IDC_EDIT_REVIVE_GATE            1126
#define IDC_EDIT_NAME                   1127
#define IDC_COMBO_ACTION                1128
#define IDC_EDIT_ACTION_TIME            1129
#define IDC_EDIT_ACTION_X               1130
#define IDC_EDIT_ACTION_Y               1131
#define IDC_EDIT_ACTION_Z               1132
#define IDC_EDIT_ACTION_NUM             1133
#define IDC_BUTTON_ACTION_POS           1134
#define IDC_BUTTON_ACTION_SAVE          1135
#define IDC_BUTTON1                     1135
#define IDC_BUTTON_ACTION_SAVE2         1136
#define IDC_BUTTON_ACTION_CLOSE         1136
#define IDC_BUTTON_HELPER_SEARCH        1136
#define IDC_EDIT_EX_1                   1137
#define IDC_EDIT_LEADER_INSERT          1137
#define IDC_EDIT_EX_2                   1138
#define IDC_EDIT_ACTION_TIME4           1139
#define IDC_EDIT_EX_3                   1139
#define IDC_COMBO_CROW_SEARCH           1140
#define IDC_EDIT_CROW_SEARCH            1141
#define ID_VIEW_EDITORTOOLBAR           32771
#define ID_EDIT_OPEN2                   32772
#define ID_FILE_OPEN2                   32773
#define ID_FILE_NEW32774                32774
#define ID_LEVEL_NEW                    32775
#define ID_FILE_OPEN32776               32776
#define ID_LEVEL_OPEN                   32777
#define ID_FILE_OPENEX                  32778
#define ID_LEVEL_OPENEX                 32779
#define ID_FILE_SAVE32780               32780
#define ID_LEVEL_SAVE                   32781
#define ID_SETTING_DEBUGINFO            32782
#define ID_SETTING_SOUNDBGM             32783
#define ID_SETTING_SOUNDENV             32784
#define ID_SETTING_SOUNDSFX             32785
#define ID_SETTING_RENDERCROW           32786
#define ID_SETTING_RENDERSCHEDULE       32787
#define ID_SETTING_RENDERGENPOS         32788
#define ID_SETTING_RENDERQUADTREE       32789
#define ID_SETTING_RENDERGATE           32790
#define ID_SETTING_RENDERLANDEFFECT     32791
#define ID_SETTING_RENDERSPHERE         32792
#define ID_SOUND_AA                     32793
#define ID_SETTING_RENDER_DEBUGINFO     32794
#define ID_SETTING_RENDER_CROWMODEL     32795
#define ID_SETTING_RENDER_SCHEDULE      32796
#define ID_SETTING_RENDER_GENPOS        32797
#define ID_SETTING_RENDER_QUADTREE      32798
#define ID_RENDER_RENDERGATE            32799
#define ID_SETTING_RENDER_LANDEFFECT    32800
#define ID_RENDER_RENDER_GATE           32801
#define ID_SETTING_RENDER_SPHERE        32802
#define ID_SETTING_RENDER_CROWSCHEDULE  32803
#define ID_SETTING_RENDER_CROWGENPOS    32804
#define ID_SETTING_SOUND_BGM            32805
#define ID_SETTING_SOUND_ENV            32806
#define ID_SETTING_SOUND_SFX            32807
#define ID_FOGRANGE_DEFAULT             32808
#define ID_SETTING_FOGRANGE_DEFAULT     32809
#define ID_FOGRANGE_NEAR                32810
#define ID_SETTING_FOGRANGE_NEAR        32811
#define ID_FOGRANGE_NORMAL              32812
#define ID_FOGRANGE_HIGH                32813
#define ID_FOGRANGE_200KRANGE           32814
#define ID_FOGRANGE_FOGRANGEDEFAULT     32815
#define ID_SETTING_FOGRANGE_4K          32816
#define ID_SETTING_FOGRANGE_8K          32817
#define ID_SETTING_FOGRANGE_12K         32818
#define ID_CAMERA_RESETCAMPERAPOS       32819
#define ID_CAMERA_RESETCAMERAPOS        32820
#define ID_CAMERA_CAMERASPEED500        32821
#define ID_CAMERA_CAMERASPEED1000       32822
#define ID_CAMERA_CAMERASPEED1500       32823
#define ID_SETTING_CAMERASPEED1500      32824
#define ID_SETTING_CAMERASPEED1000      32825
#define ID_SETTING_CAMERASPEED500       32826
#define ID_CAMERA_CAMERASPEEDDEFAULT    32827
#define ID_SETTING_CAMERASPEEDDEFAULT   32828
#define ID_FOGRANGE_FOGRANGE50K         32829
#define ID_SETTING_FOGRANGE_5K          32830
#define ID_SETTING_FOGRANGE_10K         32831
#define ID_SETTING_FOGRANGE_20K         32832
#define ID_SETTING_FOGRANGE50K          32833
#define ID_CAMERA_JUMP                  32834
#define ID_CAMERA_JUMPTOSPHERE          32835
#define ID_EDITCONTROL_SPHEREMATRIX     32836
#define ID_EDITCONTROL_SPHEREMATRIX32837 32837
#define ID_EDITCONTROL_SPHEREMATRIX32838 32838
#define ID_EDIT_SMATRIX_MOVE            32839
#define RIX32837                        32840
#define ID_EDIT_SMATRIX_ROTATE          32841
#define ID_EDIT_SMATRIX_SCALE           32842
#define ID_EDITCONTROL_BOX              32843
#define ID_EDITCONTROL_BOX32844         32844
#define ID_EDITCONTROL_BOX32845         32845
#define ID_EDITCONTROL_MATRIX           32846
#define ID_EDITCONTROL_MATRIX32847      32847
#define ID_EDITCONTROL_MATRIX32848      32848
#define ID_EDIT_BOX_MOVE                32849
#define ID_EDIT_BOX_SCALE               32850
#define ID_EDIT_BOX_SELSCALE            32851
#define ID_EDIT_MATRIX_MOVE             32852
#define ID_EDIT_MATRIX_ROTATE           32853
#define ID_EDIT_MATRIX_SCALE            32854
#define ID_Menu                         32855
#define ID_CURSOR_DELETEGATESELECT      32856
#define ID_DETECT_SELECT_CROW           32857
#define ID_DETECT_SELECT_GATE           32858
#define ID_LEVEL_SAVE_WLD               32859
#define ID_FILE_WLDSAVE                 32860
#define ID_RENDER_RENDERGROUPLINE       32861

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        325
#define _APS_NEXT_COMMAND_VALUE         32862
#define _APS_NEXT_CONTROL_VALUE         1138
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
