//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EditorSkill.rc
//
#define ID_LOAD_SKILL                   3
#define ID_SAVE_SKILL                   4
#define ID_LOAD_CSV                     5
#define ID_SAVE_CSV                     6
#define ID_SEARCH                       7
#define IDD_EDIT1                       101
#define IDD_EDITORSKILL_DIALOG          102
#define IDD_EDIT2                       103
#define IDD_TREE                        104
#define IDR_MAINFRAME                   128
#define IDR_MENU_EDIT                   129
#define IDD_DIALOG_SEARCH               129
#define IDD_DIALOG_SKILL                130
#define IDD_DIALOG_CROW                 133
#define IDC_STATIC_TOOL                 1000
#define IDC_STATIC_SEARCH_3             1000
#define IDC_STATIC_SEARCH_1             1001
#define IDC_STATIC_SEARCH_2             1002
#define IDC_BUTTON_PAGE_NEXT            1003
#define IDC_BUTTON_PAGE_BACK            1003
#define IDC_CHECK_LEARN                 1004
#define IDC_TREE                        1005
#define IDC_BUTTON_SEARCH               1005
#define IDC_EDIT_GRADE                  1005
#define IDC_EDIT_MAXLEVEL               1006
#define IDC_EDIT_TARRANGE               1007
#define IDC_LIST_RESULT                 1008
#define IDC_CHECK_CURE_NUMB             1008
#define IDC_CHECK_CURE_STUN             1009
#define IDC_COMBO_SEARCHTYPE            1010
#define IDC_CHECK_CURE_STONE            1010
#define IDC_COMBO_SEARCH                1011
#define IDC_CHECK_CURE_FROZEN           1011
#define IDC_CHECK_CURE_MAD              1012
#define IDC_EDIT_SEARCH                 1013
#define IDC_CHECK_CURE_POISON           1013
#define IDC_BUTTON_GO                   1014
#define IDC_CHECK_CURE_CURSE            1014
#define IDC_EDIT_X                      1015
#define IDC_CHECK_CURE_BURN             1015
#define IDC_EDIT_Y                      1016
#define IDC_EDIT_EFFECT                 1016
#define IDC_BUTTON_EFFECT_MINUS         1017
#define IDC_BUTTON_EFFECT_ADD           1018
#define IDC_BUTTON_EFF_TARGET1          1019
#define IDC_EDIT_EFF_TARGET1            1020
#define IDC_BUTTON_EFF_TARGET2          1021
#define IDC_EDIT_SEL_MID                1021
#define IDC_EDIT_SKILLID_MID            1022
#define IDC_EDIT_SEL_SID                1022
#define IDC_EDIT_SKILLID_SID            1023
#define IDC_EDIT_SEL_NAME               1023
#define IDC_EDIT_NAME                   1024
#define IDC_EDIT_NAME2                  1025
#define IDC_LIST_SELECT                 1025
#define IDC_EDIT_COMMENT                1026
#define IDC_EDIT_COMMENT2               1027
#define IDC_COMBO_EMROLE                1028
#define IDC_COMBO_EMAPPLY               1029
#define IDC_COMBO_EMTYPES               1030
#define IDC_COMBO_EMIMPACT_TAR          1031
#define IDC_COMBO_EMIMPACT_REALM        1032
#define IDC_COMBO_EMIMPACT_SIDE         1033
#define IDC_COMBO_LITEM                 1034
#define IDC_COMBO_RITEM                 1035
#define IDC_COMBO_EMELEMENT             1036
#define IDC_COMBO_EMSTATEBLOW           1037
#define IDC_COMBO_EMIMPACT              1038
#define IDC_COMBO_EMSPEC                1039
#define IDC_COMBO_EMSKILLSPECIAL        1040
#define IDC_EDIT_DELAYDAMAGE            1041
#define IDC_EDIT_EFF_TARGET2            1042
#define IDC_EDIT_SKLVL                  1043
#define IDC_COMBO_TIME_TARGET1          1044
#define IDC_COMBO_TIME_TARGET2          1045
#define IDC_BUTTON_SKLVL_MINUS          1046
#define IDC_BUTTON_SKLVL_ADD            1047
#define IDC_CHECK_EFF_SINGLE            1048
#define IDC_BUTTON_IMPACT_MINUS         1049
#define IDC_COMBO_POS_TARGET1           1050
#define IDC_COMBO_POS_TARGET2           1051
#define IDC_COMBO_ANI_MAIN              1052
#define IDC_BUTTON_IMPACT_ADD           1053
#define IDC_EDIT_REQSKILL_MID           1054
#define IDC_EDIT_REQSKILL_SID           1055
#define IDC_EDIT_REQSKILL_NAME          1056
#define IDC_BUTTON_ICON                 1057
#define IDC_EDIT_AS_LVL                 1057
#define IDC_EDIT_ICONFILE               1058
#define IDC_EDIT_ICON_INDEX_X           1059
#define IDC_EDIT_ICON_INDEX_Y           1060
#define IDC_BUTTON_CHECKREQSKILL        1061
#define IDC_BUTTON_SPEC_MINUS           1061
#define IDC_COMBO_ANI_SUB               1062
#define IDC_EDIT_ANI_MAIN               1063
#define IDC_EDIT_ANI_SUB                1064
#define IDC_BUTTON_EFF_SELF1            1065
#define IDC_EDIT_EFF_SELF1              1066
#define IDC_BUTTON_EFF_SELF2            1067
#define IDC_BUTTON_SKILL                1068
#define IDC_EDIT_EFF_SELF2              1069
#define IDC_BUTTON_LEVEL_MINUS          1069
#define IDC_BUTTON_LEVEL_ADD            1070
#define IDC_BUTTON_SPEC_ADD             1070
#define IDC_BUTTON_PAGE_CANCEL          1071
#define IDC_COMBO_TIME_SELF1            1072
#define IDC_EDIT_LEVEL                  1072
#define IDC_COMBO_TIME_SELF2            1073
#define IDC_EDIT_CDATA_DELAY            1073
#define IDC_EDIT_CDATA_DURATION         1074
#define IDC_EDIT_IMPACT_NUM             1074
#define IDC_COMBO_POS_SELF1             1075
#define IDC_EDIT_CDATA_RANGE            1075
#define IDC_COMBO_POS_SELF2             1076
#define IDC_EDIT_CDATA_STRIKENUM        1076
#define IDC_EDIT_CDATA_ANGLE            1077
#define IDC_EDIT_SPEC_NUM               1077
#define IDC_BUTTON_EFF_TARG             1078
#define IDC_EDIT_CDATA_PENETRATION      1078
#define IDC_EDIT_EFF_TARG               1079
#define IDC_EDIT_CDATA_TARGETNUM        1079
#define IDC_COMBO_TIME_TARG             1080
#define IDC_EDIT_CDATA_VALUE            1080
#define IDC_COMBO_POS_TARG_A            1081
#define IDC_STATIC_APPLY                1081
#define IDC_COMBO_POS_TARG_B            1082
#define IDC_EDIT_CDATA_HP               1082
#define IDC_BUTTON_EFF_SELFBODY         1083
#define IDC_EDIT_CDATA_MP               1083
#define IDC_EDIT_EFF_SELFBODY           1084
#define IDC_EDIT_CDATA_SP               1084
#define IDC_BUTTON_EFF_TARGETBODY1      1085
#define IDC_EDIT_CDATA_EXP              1085
#define IDC_BUTTON_EFF_TARGETBODY2      1086
#define IDC_EDIT_CDATA_ARROW            1086
#define IDC_EDIT_EFF_TARGETBODY1        1087
#define IDC_EDIT_CDATA_CHARM            1087
#define IDC_EDIT_EFF_TARGETBODY2        1088
#define IDC_EDIT_BLOW_GEN               1088
#define IDC_COMBO_TIME_SELFBODY         1089
#define IDC_STATIC_BLOW_1               1089
#define IDC_COMBO_TIME_TARGETBODY1      1090
#define IDC_STATIC_BLOW_2               1090
#define IDC_BUTTON_PAGE_SAVE            1091
#define IDC_COMBO_TIME_TARGETBODY2      1092
#define IDC_STATIC_BLOW_3               1092
#define IDC_BUTTON_EFF_HOLDOUT          1093
#define IDC_EDIT_IMPACT_NUM2            1093
#define IDC_EDIT_EFF_HOLDOUT            1094
#define IDC_EDIT_CDATA_HP_PTY           1094
#define IDC_EDIT_CDATA_MP_PTY           1095
#define IDC_EDIT_SKILLID_GROUP          1095
#define IDC_COMBO_ATTRIBUTE             1096
#define IDC_EDIT_CDATA_SP_PTY           1096
#define IDC_EDIT_AS_MID                 1097
#define IDC_EDIT_EXT_DATA               1097
#define IDC_EDIT_AS_SID                 1098
#define IDC_COMBO_EMAPPLY2              1098
#define IDC_COMBO_EMACTION              1098
#define IDC_EDIT_LEARN_LEVEL            1099
#define IDC_BUTTON_SPEC_ADD2            1099
#define IDC_EDIT_LEARN_STAT_POW         1100
#define IDC_EDIT_SPEC_NUM2              1100
#define IDC_EDIT_LEARN_STAT_SPI         1101
#define IDC_EDIT_CDATA_CP               1101
#define IDC_EDIT_LEARN_STAT_INT         1102
#define IDC_EDIT_CDATA_BULLET           1102
#define IDC_EDIT_LEARN_STAT_STR         1103
#define IDC_EDIT_SUM_MID                1103
#define IDC_EDIT_LEARN_STAT_DEX         1104
#define IDC_EDIT_SUM_SID                1104
#define IDC_EDIT_LEARN_STAT_STA         1105
#define IDC_EDIT_SUM_DELAY              1105
#define IDC_EDIT_AS_NAME                1106
#define IDC_BUTTON_EFF_TARGET3          1106
#define IDC_EDIT_LEARN_SKILLPOINT       1107
#define IDC_BUTTON_HEAD_M               1107
#define IDC_EDIT_LEARN_SKILLLEVEL       1108
#define IDC_BUTTON_UPPER_M              1108
#define IDC_STATIC_BLOW                 1109
#define IDC_EDIT_EFF_TARGET3            1109
#define IDC_EDIT_BLOW_VAR1              1110
#define IDC_COMBO_TIME_TARGET3          1110
#define IDC_EDIT_BLOW_VAR2              1111
#define IDC_COMBO_POS_TARGET3           1111
#define IDC_BUTTON_LOWER_M              1112
#define IDC_BUTTON_EFF_SELF3            1112
#define IDC_STATIC_IMPACT               1113
#define IDC_EDIT_EFF_SELF3              1113
#define IDC_EDIT_IMPACT_VAR             1114
#define IDC_COMBO_TIME_SELF3            1114
#define IDC_STATIC_SPEC                 1115
#define IDC_COMBO_POS_SELF3             1115
#define IDC_BUTTON_HAND_M               1116
#define IDC_EDIT_EX_DATA_1              1116
#define IDC_EDIT_SPEC_VAR1              1117
#define IDC_EDIT_EX_DATA_2              1117
#define IDC_EDIT_SPEC_VAR2              1118
#define IDC_EDIT_EX_DATA_3              1118
#define IDC_STATIC_SPEC_1               1119
#define IDC_EDIT_EX_DATA_4              1119
#define IDC_STATIC_SPEC_2               1120
#define IDC_EDIT_EX_DATA_5              1120
#define IDC_BUTTON_LHAND_M              1121
#define IDC_EDIT_LEARN_SKILLLEVEL2      1121
#define IDC_EDIT_REQMONEY               1121
#define IDC_BUTTON_RHAND_M              1122
#define IDC_BUTTON_FOOT_M               1123
#define IDC_BUTTON_FACE_M               1124
#define IDC_EDIT_HEAD_M                 1125
#define IDC_EDIT_SUM_LIFE               1126
#define IDC_EDIT_SPS_EFFECT             1127
#define IDC_EDIT_UPPER_M                1128
#define IDC_EDIT_LOWER_M                1129
#define IDC_EDIT_HAND_M                 1130
#define IDC_EDIT_LHAND_M                1131
#define IDC_EDIT_RHAND_M                1132
#define IDC_EDIT_FOOT_M                 1133
#define IDC_EDIT_FACE_M                 1134
#define IDC_BUTTON_HEAD_F               1135
#define IDC_BUTTON_UPPER_F              1136
#define IDC_BUTTON_LOWER_F              1137
#define IDC_BUTTON_HAND_F               1138
#define IDC_BUTTON_LHAND_F              1139
#define IDC_BUTTON_RHAND_F              1140
#define IDC_BUTTON_FOOT_F               1141
#define IDC_BUTTON_FACE_F               1142
#define IDC_EDIT_HEAD_F                 1143
#define IDC_EDIT_UPPER_F                1144
#define IDC_EDIT_LOWER_F                1145
#define IDC_EDIT_HAND_F                 1146
#define IDC_EDIT_LHAND_F                1147
#define IDC_EDIT_RHAND_F                1148
#define IDC_EDIT_FOOT_F                 1149
#define IDC_EDIT_FACE_F                 1150
#define IDC_EDIT_SPS_DURATION           1151
#define IDC_BUTTON_HEAD_M2              1152
#define IDC_BUTTON_SPS_EFFECT           1152
#define IDC_EDIT_IMPACT_VAR2            1153
#define IDC_EDIT_SPEC_VAR3              1154
#define IDC_EDIT_SPEC_VAR4              1155
#define IDC_EDIT_SUM_NUM                1156
#define IDC_EDIT_SUM_SKILLLEVEL         1157
#define IDC_BUTTON_SUM_CROW             1158
#define IDC_EDIT_SUM_CROWNAME           1159
#define IDC_EDIT_CDATA_DATA             1160
#define IDC_COMBO_DEBUFF_ACTION         1161
#define IDC_STATIC_DEBUFF               1162
#define IDC_STATIC_ACTION               1163
#define IDC_COMBO_ANI_SUB2              1164
#define ID_TOOL_ADD                     32771
#define ID_TOOL_DELETE                  32773
#define ID_TOOL_COPY                    32774
#define ID_TOOL_PASTE_VAL               32777
#define ID_TOOL_PASTE_NEW               32778
#define ID_TOOL_EDIT1                   32779
#define ID_TOOL_EDIT2                   32781

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1165
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
